### ISSUE TITLE
Resizing terminal after 'clear' command reveals cleared text

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/terminal#100]
![screenshot from 2017-05-30 06 36 03](https://cloud.githubusercontent.com/assets/20795161/26570872/4bb08346-4502-11e7-9458-cdd739b1d048.png)

**Comment by SubhadeepJasu** [comment]
Same happens when using search box.

**Comment by yumiris** [comment]
This is common for most Terminal emulators. Use the `reset` command to actually dispose the previous output.
