### ISSUE TITLE
Add support for panes

### ISSUE THREAD

**Issue by Appeltabak** [elementary/terminal#102]
I would really love support for splitting up the window into multiple panes / multiplexed terminals as seen in [Terminator](https://gnometerminator.blogspot.nl/) and [tmux](https://tmux.github.io/). I think it gives a bit more of an overview when working on multiple things simultaneously compared to Tabs.

**Comment by danrabbit** [comment]
Managing windows is the responsibility of the window manager. We should try to re-implement window management inside each app

**Comment by Appeltabak** [comment]
@danrabbit I definitely agree, but starting e.g. four Terminals and manually aligning them so I can see at one glance how several related processes are doing, is quite cumbersome, I think. Especially when need to do that everything after reboot / startup.

**Comment by Appeltabak** [comment]
@danrabbit What would you suggest to make this less cumbersome? (If you think this isn't an general issue at all, please let me know ;p )

**Comment by danrabbit** [comment]
@Appeltabak This is an issue in Gala. Quarter tiling is a known feature request

**Comment by jeremypw** [comment]
There is a pending branch in Pantheon Files that arranges new windows in a grid instead of on top of each other - however, as Dan said, maybe this does intrude upon the responsibilities of the window manager?

**Comment by ibnesayeed** [comment]
> @danrabbit: Managing windows is the responsibility of the window manager. We shouldn't try to re-implement window management inside each app

We should not be too religious about not re-implementing certain features in specific apps where they make more sense and improve usability and experience. Being able to split the terminal horizontally and vertically is the only reason why I use `terminator` instead of the bundled `terminal`. The argument of window management responsibility can also be put for tabs, because, conceptually those are also separate windows put together. Many IDEs and text editors (including terminal based editors like Emacs) implement internal pane management because it is really very useful and productive in that context.

If I use multiple terminals without panes, then I have two choices; 1) I can either open them in tabs, which means I can only see one at a time or 2) I can open many small windows and arrange them on the screen like tiles, which means once other applications like a web browser, a text editor, and many others covers them, I lose the ability to bring all the terminals into view at once.

**Comment by Philip-Scott** [comment]
@ibnesayeed @Appeltabak If you guys really need to split the terminal, you guys can use the command `tmux` inside of the terminal to do something like:

![screenshot from 2017-09-20 10 14 42](https://user-images.githubusercontent.com/10786508/30651893-93b3bc06-9dec-11e7-877f-5cac8ec53e57.png)

see https://tmuxcheatsheet.com for more details

**Comment by ibnesayeed** [comment]
Thanks @Philip-Scott, `tmux` is really a great tool. I have used it in the past. It does much more than what this request ask for. Native pane splitting support would be great to this terminal.

**Comment by Appeltabak** [comment]
@Philip-Scott Yeah, that's the probably the best way for now to get the functionality inside Terminal. Less intuitive at first and a stronger learning curve, but more productive at the long term thought.

Thanks for the cheat sheet!

**Comment by dustinleblanc** [comment]
While I agree that tmux is awesome, and I also agree that keeping the scope of apps small is a good idea, panes/splits in terminals are so incredibly useful. Doing so via tmux/screen is definitely a power user way to go, but I would absolutely love to have native terminal splits in Elementary's terminal similar to iterm/tilix. Keeping them as a single terminal window is also quite useful (vs tiling several separate terminals). I most commonly use this for running multiple related processes (webserver, watcher/compiler, and a third window for continuing one off commands).

All that to just say +1, it'd be a cool feature that would help Elementary be that much better as a default OS for the web dev crowd.

**Comment by dcharbonnier** [comment]
tmux is over complicated, the vim of the terminal.
On most of what I'm doing I need at least 4 terminal open, one task one tab, 4-8 split panes on each tabs.
This terminal is as good as the mac one, and everybody use iTerm on mac for this reason.
A simple efficient terminal is a core feature  for developers and is missing on elementaryos. 
There is other linux terminals (I'm using terminator) that provide this feature but if I picked elementary it's to avoid using this kind of apps.

**Comment by ibnesayeed** [comment]
@danrabbit please reconsider this. It is one of those things that is worth duplicating the effort. We generally have system-wide file chooser dialog and file manager app, but still add the file tree in text editors because that is very handy. The same goes with panes in terminal, in my opinion.

**Comment by dcharbonnier** [comment]
I found https://github.com/gnunn1/tilix that looks like a perfect replacement for the Terminal with panes support

**Comment by Globegitter** [comment]
I know quite a few people already commente on the topic, but I want to say I agree, I have tried tmux but personally do not seem to have the need of all the powerfeatures it provides, so it just overcomplicates the setup. Having missing support of this is also my only reason I am using terminator currently and now going to look into tilix also.

**Comment by deyvisonrocha** [comment]
Please reconsider this!

**Comment by dawidmalina** [comment]
I would be super happy if the elementary terminal could be iterm2 alternative.
