### ISSUE TITLE
Tab finish green check icon should reflect exit status [$15]

### ISSUE THREAD

**Issue by btkostner** [elementary/terminal#109]
## What currently happens

When a command finishes on a non focused tab, a green check icon appears.

## What I expect to happen

When a command finishes successfully (exit code 0), a green check icon appears. Otherwise a red cross icon appears indicating that the command did not finish successfully

---
This issue has a bounty [on bountysource](https://www.bountysource.com/issues/46421213-tab-finish-green-check-icon-should-reflect-exit-status)

**Comment by donadigo** [comment]
I've managed to make this work, but I needed to move the `PROMPT_COMMAND` envvar to the bashrc file because for some unknown reason, it doesn't work inside actual code.
