### ISSUE TITLE
Hide Tab Bar with Only One Tab

### ISSUE THREAD

**Issue by MggMuggins** [elementary/terminal#118]
Hey, I really love your terminal! It's light, and it just works. Anyway, I had a thought that I decided to share, just in case somebody thought it was a good idea.
Terminal tabs are a good idea. However, when I only have one tab open, that tab bar takes up quite a bit of space. I think it would be really cool if the terminal would hide the tab bar if you have only one tab open. PCManFM and its Qt port over at Lxde/LxQt do this with their tab bars, and I really like it. Feel free to close this issue if it isn't something you're willing to do.

**Comment by cassidyjames** [comment]
@MggMuggins this is actually a hidden feature of Terminal right now, it's just not exposed in the UI. Of course being a hidden feature, it's pretty much untested and not guaranteed to stick around, but you can enjoy it for now. :)

Enter `gsettings set org.pantheon.terminal.settings tab-bar-behavior 'Hide When Single Tab'` into the terminal, then close and reopen it. To go back to the default behavior, enter `gsettings reset org.pantheon.terminal.settings tab-bar-behavior`.

**Comment by MggMuggins** [comment]
That is actually amazing. Thanks very much!
