### ISSUE TITLE
Cycle tabs shortcut

### ISSUE THREAD

**Issue by Nine-H** [elementary/terminal#124]
you can use ctrl+shift+left/right to move tabs, I want a fast cycle with ctrl+shift+tab. In general I prefer one handed and left handed chords because I can keep using the mouse.

**Comment by liamkinne** [comment]
I've just forked this repo and made an addition that gives the functionality to cycle through tabs, but I have a small issue. I too agree that the command should be something like ctrl+shift+tab but I can't figure out how to get 'tab' working with gtk. If I try and use `<Control><Shift><Tab>` I get the error: `Unable to parse accelerator '<Control><Shift><Tab>'`

I'm new to gtk and I can't seem to find a reference to the list of key names etc. If someone more experienced could give me a hand that would be great.

Right now it is mapped to `<Control><Shift>h` just to see that it actually works. [Here's my fork](https://github.com/liamkinne/terminal)

**Comment by liamkinne** [comment]
It appears that there is no Gtk accelerator for <Tab>... which is annoying.

**Comment by donadigo** [comment]
@liamkinne look here: https://github.com/elementary/wingpanel/blob/master/src/PanelWindow.vala#L71

**Comment by janxkoci** [comment]
Epiphany browser uses Ctrl+Tab shortcut to cycle through tabs (as all other browsers do) and it's GTK3, so maybe you can get inspiration there... Sorry I can't help more..

**Comment by janxkoci** [comment]
Actually even elementary Files can cycle through tabs with Ctrl+Tab. You can try to look in the code there..

**Comment by jeremypw** [comment]
This is fixed in elementary 6.0 so closing.
