### ISSUE TITLE
Position of the magnifier (Search...) on the left side (?)

### ISSUE THREAD

**Issue by J0Ar** [elementary/terminal#144]
Perhaps it's me, but after @danrabbit showed/added the [zoom option](https://github.com/elementary/terminal/pull/142), I think it's a little bit misleading to have a 'magnifier-icon' (for search) besides a 'zoom-option' (for charakter size).
Maybe the magnifier-icon (search) could then be placed on the left side...i think, in the current state, when you click on the 'search', the search-box opens at the left side anyway.
Just a suggestion/idea :)
![bildschirmfoto von 2017-09-27 21 19 34](https://user-images.githubusercontent.com/23266409/30933028-994b1140-a3c9-11e7-8b5c-f54307ef5e49.png)

**Comment by cassidyjames** [comment]
Interesting. Traditionally elementary apps have had search at the top-right of the window, which I believe is why we put it there in Terminal.

It's also important to note that the view settings (like character size) are expected to be joined by other view options, like light/dark theme. So it's not really a zoom option. But I see the point with the current implementation.

**Comment by J0Ar** [comment]
Ok, lets wait for the next release. I think i was a little bit fast by creating this 'issue' because at this time the code was just too young and work in progress. So I will close this issue (for now^^)
