### ISSUE TITLE
Consider using themes

### ISSUE THREAD

**Issue by donadigo** [elementary/terminal#147]
I think it would be nice if we could expose a way in the UI for the user to set some pre-made themes like we do in Code.

This requires some things to solve. How do we want to store theme information? Is there an available standard format that's already doing that? If not, do we want to create one from scrach?

**Comment by Nine-H** [comment]
there's a bunch of themes here https://github.com/Mayccoll/Gogh not sure how to store them, might be worth looking at other terminal emulators.

**Comment by danrabbit** [comment]
The color scheme is in a dconf key right now, but it's not in a super convenient format.

As far as storing/loading theme information in a more sane way I think my first reaction would be to try to interpret Gtk.SourceView themes so we don't have to invent a new theme format.

As for exposing them in the UI, I would really like to do something like how BookWorm exposes theme options. This way we could intelligently switch both the color scheme of the Terminal and the Gtk stylesheet at the same time. I would suggest just three options: Solarized Light, Solarized Dark, and a popular white color scheme. Then if you want something more complex you could use dconf as you would today.
