### ISSUE TITLE
Broken paste

### ISSUE THREAD

**Issue by Djaler** [elementary/terminal#148]
https://github.com/elementary/terminal/commit/3f62e3d023dd43bfd035617e9801eac190d22ad8 This commit break paste for me.
In zsh, if I paste something, for example 'text', i have this in terminal
![image](https://user-images.githubusercontent.com/7964583/31058238-183c2642-a6f9-11e7-8f16-00e226d8468e.png)

**Comment by LightSunrider** [comment]
I'm sorry that my changes has caused you inconvenience. I also use zsh, but I have no such problem arose. Thank you for correcting my mistake.
