### ISSUE TITLE
Middle click copy paste logic is broken

### ISSUE THREAD

**Issue by mpkh** [elementary/terminal#150]
I can't paste selected text with middle click, it pastes what I have in clipboard and it's wrong!
It should paste what I have selected

**Comment by LightSunrider** [comment]
I'm sorry. My commit broke this feature. I have already started to solve this problem.
[102508bb09cf21b1de035ca41919c68bc6dc2f20](https://github.com/LightSunrider/terminal/commit/102508bb09cf21b1de035ca41919c68bc6dc2f20)

**Comment by LightSunrider** [comment]
#151 fixes this issue.
