### ISSUE TITLE
All tab titles disappear after closing any single tab when no ~/.bashrc

### ISSUE THREAD

**Issue by Extravert-ir** [elementary/terminal#154]
Steps to reproduce
1. Open several tabs in terminal
![screenshot from 2017-10-11 23-39-06](https://user-images.githubusercontent.com/961957/31465760-92779d24-aedd-11e7-958d-d64caa6b009d.png)
2. Close any tab (either with middle-click or with close button)
![screenshot from 2017-10-11 23-39-15](https://user-images.githubusercontent.com/961957/31465800-bee9cf44-aedd-11e7-8134-209e1d7d4240.png)
The tab is closed but other tabs' titles disappear too

**Comment by LightSunrider** [comment]
Can you tell in more detail please? What distro do you use? How long ago did this problem arise (maybe after the update)? 

I couln't reproduce this bug in elementary. But I was able to reproduce these in Archlinux (with KDE). 
I built a terminal by this script:
```
git clone https://github.com/elementary/terminal.git
cd terminal
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE='Release' \ 
         -DCMAKE_INSTALL_PREFIX='/usr' \
         -DGSETTINGS_COMPILE='FALSE'
make
```
Very strange, I think the problem is in some library. :thinking:

**Comment by Extravert-ir** [comment]
Found the reason of such behaviour. I have no .bashrc file in my home folder. So when I copied Ubuntu 16.04 default one to my $HOME, everything works fine.
The guilty expression is:
```
PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
```
which forces terminal to set its title (default config does not do it).
PR #87 introduces this problem if I'm not mistaken

**Comment by jeremypw** [comment]
The tabs should not normally be named "Terminal" but default to "Home".

**Comment by jeremypw** [comment]
Confirmed that removing ~/.bashrc causes the problem.
