### ISSUE TITLE
Terminal should close after hitting CTRL Q

### ISSUE THREAD

**Issue by snowparrot** [elementary/terminal#159]
Wished behaviour

To put in line with other apps terminal should close after hitting CTRL + Q

**Comment by davidmhewitt** [comment]
CTRL + Q is an escape sequence used in the terminal itself, so it shouldn't be overridden by a shortcut to close the application.

To maintain compatibility with all expected virtual terminal behavior, there are lot of shortcuts that can't be implemented directly, like CTRL + T.

If you're curious what it's used for:
CTRL + S should prevent the terminal from scrolling automatically, so you can freeze the output in a fast scrolling terminal. CTRL + Q should then re-enable scrolling again.
