### ISSUE TITLE
keyboard shorcuts are not discoverable

### ISSUE THREAD

**Issue by josephholsten** [elementary/terminal#164]
There doesn't seem to be any obvious link to documentation, and I can't seem to find it on my own. Unless we're really planning on read-the-source being the official documentation.

I'm assuming that the the lack of discoverability is the reason I can't currently to switch between tabs with  a keyboard shortcut. Surely there actually is one, right?

**Comment by josephholsten** [comment]
If RTFS was the doc, then the resolution is: https://github.com/elementary/terminal/blob/master/src/PantheonTerminalWindow.vala#L116

**Comment by cassidyjames** [comment]
In GTK 3.20+, we could theoretically add a keyboard button to the titlebar to show a keyboard shortcut sheet.

**Comment by josephholsten** [comment]
BTW, I'm having similar difficulty finding the keybindings for epiphany, but can't figure out what repo to file against. Could I get a pointer?

**Comment by bil-elmoussaoui** [comment]
Eiphany already ships the shortcuts widgets which is new (on gtk3.20) and elementary ships eiphany with gtk 3.18 :) you will have to wait for the newer version of elementary

**Comment by josephholsten** [comment]
Ah fun. Is there a repo for the elementary fork of epiphany, or would I normally just file bugs with upstream?

**Comment by danrabbit** [comment]
I'm going to close this because menu items now show keyboard accelerators and toolitems show them in their tool tips.

Please feel free to open new issues specifying if there is a particular missing shortcut and what that shortcut is
