### ISSUE TITLE
Switch for auto theming day / night

### ISSUE THREAD

**Issue by donadigo** [elementary/terminal#167]
I think it actually could be nice if you had a switch for automatically switching between light and dark themes according to the current time. The color options would be then insensitive if the setting would be enabled.

**Comment by danrabbit** [comment]
Some relevant discussion from slack: @cassidyjames brought up the point that whether or not he wants to use a light or dark style is more typically correlated with the lighting in the room than it is with a certain part of the day

**Comment by megatux** [comment]
Nice feature. I would like to see it applied to the complete desktop env. I usually work from morning to dawn and during the day I manually have to adjust theme colors for several apps (my code editor, terminal, browser, etc) F.lux helps a little, but it would be very nice to have something integrated into the DE. Could someone point me where to add this feature request in E OS?

**Comment by donadigo** [comment]
@megatux the closest would be the window manager: https://github.com/elementary/gala, although I suppose we would need to create a new project for an agent that would take care of that, but first I suggest that you fill an issue to gala so that team members can discuss it there.

**Comment by cassidyjames** [comment]
Superseded by #618 as the scheduling would then be handled at the system level.
