### ISSUE TITLE
Sorting algorithm is different than Files

### ISSUE THREAD

**Issue by nkkollaw** [elementary/terminal#176]
I have no idea where the sorting algorithm comes from--whether from the kernel, distro, or whatever, but when I list files using `ls -lah` the order is different than when sorting the same directory using Files.

It's very confusing.

**Comment by jeremypw** [comment]
Use the `--group-directories-first` flag with `ls` to sort the listing the same way as Files (when Files is sorting on filename).  Use the `--sort=size or -S`, `--sort=time or -t`, `--sort=extension or -X` to match other Files sort settings.

**Comment by nkkollaw** [comment]
I see. Thanks for your suggestions.

What I don't understand is that Ubuntu Server groups items together and sorts them alphabetically  (so, dotfiles first).

So, I guess there's some configuration at the OS level, of is it Ubuntu Server just different?

**Comment by jeremypw** [comment]
Files has its own internal sorting algorithm and it is not user configurable at the moment. It sorts hidden files after normal files within each group.

**Comment by danrabbit** [comment]
I'm +1 on making ls sorting match Files, but that would be something to file against the default settings package. I'm going to close this here since it can't be fixed in Terminal and move discussion to this new issue: https://github.com/elementary/default-settings/issues/8
