### ISSUE TITLE
Support clearing the screen mid process (Reset + Clear)

### ISSUE THREAD

**Issue by nitaigao** [elementary/terminal#181]
CTRL-L will only clear the window when the bash shell is ready for a command.

If for instance you have a server process running with many logs, you need to clear the window to get rid of the clutter then currently its not possible unless you exit the process, hit CTRL-L and restart the process.

This is possible in Gnome Terminal with Reset + Clear and in OSX Terminal with CMD + K

**Comment by osman** [comment]
moreover CTRL-L is the same as `clear`, which does not clear scollback.

`Reset + Clear` and `CMD + K` work like `tput reset` in bash, which does clear scrollback. Super useful
