### ISSUE TITLE
Change shell?

### ISSUE THREAD

**Issue by FFY00** [elementary/terminal#191]
Is there any way of changing the shell? If not, could we implement a `-e` argument that gets a value like `/usr/bin/fish`?

Thanks in advance.

**Comment by Djaler** [comment]
You can change default shell using `chsh -s /usr/bin/fish`

**Comment by adab4d** [comment]
Use GSettings with schema `org.pantheon.terminal.settings` and `shell` key:

    gsettings set org.pantheon.terminal.settings shell /path/to/new/shell

I think this is preferred over using *chsh* since the latter would change login shell as well.
