### ISSUE TITLE
how do i fix .bashrc error ?

### ISSUE THREAD

**Issue by nurazhar** [elementary/terminal#192]
bash: /home/username/.bashrc: line 171: syntax error near unexpected token `PATH=$HOME/bin:$PATH'
bash: /home/username/.bashrc: line 171: `esacexport PATH=$HOME/bin:$PATH'

i can't figure this our on the terminal

**Comment by Bat41** [comment]
This is not related to elementary Terminal, but I think you can fix your issue by replacing the problematic line (use Scratch or something else that doesn't require a terminal) with `PATH='$HOME/bin:$PATH'`.
