### ISSUE TITLE
Terminal not in focus

### ISSUE THREAD

**Issue by Djaler** [elementary/terminal#203]
After terminal open, I can't write commands, because shell area not in focus. I need to click on it.

Version - 0.4.3+r1047

**Comment by btkostner** [comment]
This is probably because of https://github.com/elementary/gala/issues/1

**Comment by Djaler** [comment]
I pretty sure this is a new bug. It appeared just recently.

**Comment by Thalexander** [comment]
This is a bug in terminal, the focus isn't given to the widget but to the tab when restoring.

**Comment by Djaler** [comment]
Also, this is precisely not a gala bug, because terminal window is in focus (i can use Ctrl+plus for example). But typing doesn't work until I click

**Comment by btkostner** [comment]
Oh, my bad. I didn't think the window was getting focused.
