### ISSUE TITLE
Help parameter will close open terminal instances

### ISSUE THREAD

**Issue by Thalexander** [elementary/terminal#205]
When running io.elementary.terminal -h any open windows will close. Other parameters such as version work as expected and do not affect open windows.

**Comment by jeremypw** [comment]
Also happens with e.g. Files and Code so not a specific Terminal problem.

**Comment by jeremypw** [comment]
Does not happen with Mate Terminal

**Comment by jeremypw** [comment]
If automatic --help support is enabled (see g_option_context_set_help_enabled()), and the argv array contains one of the recognized help options, this function will produce help output to stdout and call exit (0).
Since Terminal is a unique instance, it closes along with any windows open.

**Comment by danrabbit** [comment]
This doesn't seem to be the case anymore. Please reopen if you can reproduce :)
