### ISSUE TITLE
Readme has wrong command to enable notifications for zsh

### ISSUE THREAD

**Issue by riteshshrv** [elementary/terminal#206]
Readme: `builtin . /usr/share/io.elementary.terminal/enable-zsh-completion-notifications || builtin true`
Correct: `builtin . /usr/share/pantheon-terminal/enable-zsh-completion-notifications || builtin true`

**Comment by Thalexander** [comment]
For the current master the readme is correct, the file location was changed by #132

**Comment by riteshshrv** [comment]
@Thalexander closing this issue, as its already resloved.
