### ISSUE TITLE
Terminal does not rememer order of tabs between restarts

### ISSUE THREAD

**Issue by Shnatsel** [elementary/terminal#211]
Steps to reproduce:

1. Start Terminal
1. Type `mkdir 1 && mkdir 2 && cd 1`
1. Open another tab in Terminal
1. Type `cd ../2`
1. Drag tab 2 before tab 1
1. Close terminal
1. Open terminal
1. :boom: observe tab order being (1,2), not (2,1)

Video of it in action: https://youtu.be/rJjFzPTugV4

Found in Loki, Terminal version `0.4.3-0~r995+pkg50+r1~ubuntu0.4.1.1`

**Comment by danrabbit** [comment]
Duplicate of #14 

Make sure to test with master ;)
