### ISSUE TITLE
Ctrl+V vim shortcut, make it possible to switch off Ctrl+V for pasting text

### ISSUE THREAD

**Issue by mambusskruj** [elementary/terminal#212]
Hi, I use Vim as my terminal text editor. One of the vim features — shortcut for visual selection. But it is conflict with elementary-terminal which paste text from buffer. Is it possible to provide users an option for turning it off? Generally the shortcut for pasting text in terminal emulator: Ctrl+Shift+V.

**Comment by Shnatsel** [comment]
If you install dconf-editor and navigate to `org.pantheon.terminal.settings`, you can toggle this behavior using the `natural-copy-paste` setting.

As someone who uses the terminal heavily, I'd appreciate this setting being exposed in UI, along with `follow-last-tab`

**Comment by jlnr** [comment]
Conversely, as someone who *always* uses GUI text editors, I'd love to have *all* UI shortcuts work without Shift, e.g. Ctrl+T for a new tab, Ctrl+W to close the current tab, etc. I'd love to see three options: 1) No natural copy & paste, 2) Natural copy & paste (default), 3) "Natural everything".

**Comment by voldyman** [comment]
since terminal is ... well a terminal, i think `gsettings set org.pantheon.terminal.settings natural-copy-paste` should be an acceptable solution.

**Comment by Shnatsel** [comment]
Thing is, this is very unusual and confusing behavior for terminal. I keep running into situations when I keep mashing "Ctrl+C" and wondering _why won't the process stop._ So the problem as I see it has several parts:

1. Understand what's going on - why won't Ctrl+C stop processes?! Why won't some essential shortcuts in vim work?!
1. After the user is aware of the "Ctrl+C means copy" behavior, there should be a way to let the user know that it can be changed at all.
1. Explain to the user how to change it.

It is hard to communicate "run `gsettings set org.pantheon.terminal.settings natural-copy-paste` to toggle Ctrl+C action" to the user. Terminal itself does not have, and [should not need](https://xkcd.com/1343/), a manual. We do have a settings dropdown, but putting "run this command" in there would be very weird and take up a lot of space. It would be much easier to put a graphical switch in there.

As for (1), it would probably be a good idea to provide some kind of feedback - in-app notification (those are a thing in GTK now, right?), or a desktop notification failing that.

**Comment by jlnr** [comment]
I have also run into the issue where I press Ctrl+C repeatedly and nothing happens because I still have a selection from earlier before. Unrelated suggestion: Maybe pressing Ctrl+C should copy *and deselect* text, so that mashing it still works?

**Comment by jeremypw** [comment]
It should be possible to stop Terminal processing Ctrl+V when there is a foreground process - i.e. when vim is running.

**Comment by jeremypw** [comment]
I suggest separate a issue be raised regarding Ctrl+C as it is confusing to extend the scope of the issue in the comments.

**Comment by jeremypw** [comment]
The linked PR causes vim etc to behave as expected without the need for a setting.

**Comment by voldyman** [comment]
But it will break the workflow for anyone who doesn’t use vim.

The mental model went from
* use ctrl-c/v top copy-paste 

To 

* ctrl-c/v only works in the shell 

Which people will translate into ctrl-c/v works *sometimes*

**Comment by Shnatsel** [comment]
@voldyman the issue is about a problem, let's discuss the specific solution in the PR

**Comment by voldyman** [comment]
@Shnatsel I agree, I should have posted the comment on the PR.

**Comment by her** [comment]
I think this could be solved elegantly by separating copy-paste and window behavior to something like 

SUPER+c 
SUPER+v 
SUPER+t
SUPER+w
etc.

**Comment by cassidyjames** [comment]
I keep hearing about this behavior interfering with legacy/Terminal as. I honestly wonder if this works be worth having a switch for smart copy/paste in the menu, on by default. Thoughts @danrabbit?

**Comment by danrabbit** [comment]
There is now an option in the menu to disable natural copy/paste :)
