### ISSUE TITLE
ZSH and FISH integration is not updated to the new D-bus API for completion notifications

### ISSUE THREAD

**Issue by Shnatsel** [elementary/terminal#214]
Apparently only BASH integration for process completion notifications has been updated to report exit code to the terminal. `src/Widgets/TerminalWidget.vala` contains the following line:

 `const string SEND_PROCESS_FINISHED_BASH = "dbus-send --type=method_call --session --dest=io.elementary.terminal /io/elementary/terminal io.elementary.terminal.ProcessFinished string:$PANTHEON_TERMINAL_ID string:\"$(history 1 | cut -c 8-)\" int32:\$__bp_last_ret_value >/dev/null 2>&1"`

But `data/enable-fish-completion-notifications` still uses the old interface: `dbus-send --type=method_call --session --dest=io.elementary.terminal /io/elementary/terminal io.elementary.terminal.ProcessFinished string:$PANTHEON_TERMINAL_ID string:"$argv[1]";`

Same goes for `data/enable-zsh-completion-notifications`

Aside of not reporting the exit code, I'm not sure that would even work on Juno for completion reporting.

**Comment by Shnatsel** [comment]
FISH integration is updated in #243

I've tried to update the ZSH integration by adding `int32:$?` to the end of the `dbus-send` command, but it always returns 0 - even when running `sleep 3; false` in the shell. Someone more familiar with ZSH than me should take a look.

**Comment by codygarver** [comment]
Closed via PR #243

**Comment by codygarver** [comment]
Sounds like ZSH needs a separate issue.
