### ISSUE TITLE
Show the command's success/error in the notification

### ISSUE THREAD

**Issue by megatux** [elementary/terminal#216]
Wishlist. Maybe a small green/red icon to know if the result code from the executed command was 0. Is it possible?

**Comment by donadigo** [comment]
This is already a thing in master, but I don't think it was released yet. Closing.

**Comment by danrabbit** [comment]
AFAICT, notifications only say "Task finished". It doesn't say whether it exited successfully or with an error

**Comment by danrabbit** [comment]
Seems like this is a duplicate of #37
