### ISSUE TITLE
hide tab bar on single tab 

### ISSUE THREAD

**Issue by ho3ein-mola** [elementary/terminal#218]
this not work Loki and now on daily PPA does not work 

```
gsettings set org.pantheon.terminal.settings tab-bar-behavior 'Hide When Single Tab'
```

**Comment by Thalexander** [comment]
On daily due to the RDNN efforts you now would use

``gsettings set io.elementary.terminal.settings tab-bar-behavior "Hide When Single Tab"``

**Comment by galah92** [comment]
On Juno I get

    GLib-GIO-Message: 12:06:18.949: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

After restarting the terminal app, this doesn't seem to work. Is it changed again?

**Comment by galah92** [comment]
> > On Juno I get
> > ```
> > GLib-GIO-Message: 12:06:18.949: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
> > ```
> > After restarting the terminal app, this doesn't seem to work. Is it changed again?
> 
> Im running Juno. This worked for me.
> `gsettings set io.elementary.terminal.settings tab-bar-behavior "Hide When Single Tab"`

Thanks. Same command as I posted, and I still get that error. Why is that? What can be done?
