### ISSUE TITLE
can't build with vte 0.52 +

### ISSUE THREAD

**Issue by cnd** [elementary/terminal#224]
```
TerminalWidget.vala:439.38-439.43: error: Argument 1: Cannot convert from `unowned string?' to `unowned char[]?'
                    this.feed_child (uris_s, uris_s.length);
                                     ^^^^^^
```

vte 0.52.0
glib 2.56.0

**Comment by rkn** [comment]
```
../pantheon-terminal-9999/src/Widgets/TerminalWidget.vala:439.38-439.43: error: Argument 1: Cannot convert from `unowned string?' to `unowned char[]?'
                    this.feed_child (uris_s, uris_s.length);
                                     ^^^^^^
../pantheon-terminal-9999/src/Widgets/TerminalWidget.vala:447.42-447.45: error: Argument 1: Cannot convert from `unowned string?' to `unowned char[]?'
                        this.feed_child (data, data.length);
                                         ^^^^

```

**Comment by decathorpe** [comment]
I can confirm this error, it prevents me from building this package on fedora 28+.

**Comment by rkn** [comment]
@decathorpe you can use my patch (appstream removal is optional for you possibly)

https://github.com/Heather/gentoo-gnome/blob/master/x11-terms/pantheon-terminal/files/no-appstream.patch

**Comment by CameronNemo** [comment]
can we reopen this please?

**Comment by cnd** [comment]
@CameronNemo it was fixed for me

_but I've stopped using this because it leaks like hell and eats 2gb ram lol_

**Comment by CameronNemo** [comment]
indeed it is fixed. wow 2 GB of RAM! nowhere close to that over here.

**Comment by cnd** [comment]
@CameronNemo well I use alike 7 tabs and there are a lot of text/compilation and I don't turn it off for weeks 😄 and well, default gnome terminal doesn't grow like that
