### ISSUE TITLE
Terminal doesn't respond to keyboard

### ISSUE THREAD

**Issue by Trudko** [elementary/terminal#231]
When running commands requiring multiple confirmations terminal stops responding. 
For example, when running npm init, terminal is stuck after confirming name for a project. Terminal cursor is blinking but it doesn't respond to pressing enter, CTRL+w, esc or anything else. Sames happens if I use gnome-terminal, virtual terminal(ctrl-alt-f1), xterm, so might be related to my settings. 

```
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (myProject) 
version: (1.0.0) 
```
Steps to reproduce:
1. run npm init
2. press enter on package name
3. you should see cursor but it won't respond to keyboard.

I tried this also with surge.sh project so it's not related to npm.

**Comment by Trudko** [comment]
NVM after closer investigation it seems that my .bashrc config was corrupt. Sorry for making rubber duck out of this issue.

**Comment by anak-ut** [comment]
hello

i got same issue with the terminal after executing some command.
the terminal didn respond, it couldnt be closed.

if we open another terminal and do top, the unresponsive terminal wasnot detected in monitor( in top) as a running program.

to temporarly overcome this, i decided to log out and re-login


voila the dead terminal disappeard
