### ISSUE TITLE
Notifications are busted

### ISSUE THREAD

**Issue by danrabbit** [elementary/terminal#236]
We broke something. Notifications no longer work in Juno daily

**Comment by itoshkov** [comment]
I'm a bit confused by this issue. On the one hand it's labeled as "In Progress", bun it's also closed.

In any rate I think this is still broken in Juno. An easy way to test it is to run a command like "sleep 3" and switch to another workspace. I'd expect to see a notification when the command finishes, but there is none.

**Comment by btkostner** [comment]
@itoshkov I just ran `sleep 3` and changed window focus. The notification worked for me.

`pantheon-terminal/bionic,now 5.3.3+r1269+pkg65~ubuntu5.0.1 amd64 [installed,automatic]`

**Comment by itoshkov** [comment]
@btkostner, after reading your comment I realized that I got this broken because I installed liquidprompt. I tested it on a fresh user and can confirm it works. Sorry for the false alarm.
