### ISSUE TITLE
Feature request: Drop-down-like terminal

### ISSUE THREAD

**Issue by Carlisle96** [elementary/terminal#252]
It would be nice to have a designated key to open, close, and reopen a terminal where you left off in the same sense how drop-down terminals work. ( No matter if they drop down from the top or just appear - but the key functionality seems convenient ) 

As far as i could see you can't get this feature with the normal system settings keyboard shortcuts.

**Comment by parnold-x** [comment]
You can use this
https://github.com/edipox/toggle_term

**Comment by Carlisle96** [comment]
perfect ! thanks

**Comment by Carlisle96** [comment]
excellent, thanks

**Comment by danrabbit** [comment]
Closing as Design Conflict. There are other drop down terminals if you're interesting in that, but it's outside the scope of this terminal's design
