### ISSUE TITLE
GtkHeaderBar is too tall with Adwaita

### ISSUE THREAD

**Issue by nana-4** [elementary/terminal#267]
![image](https://user-images.githubusercontent.com/9556384/41230584-4c17c0c8-6dbb-11e8-97b1-c04c7588c9a8.png)

As shown in the screenshot, Terminal's headerbar is too tall with Adwaita, the default GTK+ theme. Since a lot of third-party GTK+ themes are based on Adwaita, this issue affects those themes as well.

After a brief investigation, I found this is due to the fact that [the headerbar has `.default-decoration` style class](https://github.com/elementary/terminal/blob/be519fd08400e536973a09318d63c9ba188d0651/src/PantheonTerminalWindow.vala#L329).

I also found [this elementary's Medium article](https://medium.com/elementaryos/developer-tips-branding-your-app-a57cb44d31d3) describes 

> `.default-decoration` for slim headerbars, like in Terminal

but from my understanding, `.default-decoration` is for legacy titlebars, **not** for slim headerbars. (See https://mail.gnome.org/archives/commits-list/2014-October/msg06960.html) This headerbar is clearly not a legacy titlebar, so IMHO it should not have the style class. Would you mind removing the class for theme compatibility?

**Comment by danrabbit** [comment]
Gonna close this as a “Design conflict”. This app is designed to be used with the elementary stylesheet. You should expect to encounter issues if you use it with another stylesheet

**Comment by nana-4** [comment]
Hmm, I don't think this is a “Design conflict”. I think it's just assigning the wrong style class to improper place. If you want, you could keep the headerbar slim by adding an elementary stylesheet specific class like `.slim-headerbar` instead of `.default-decoration` while ensuring the theme compatibility.

Adwaita is not just an "_another stylesheet_", it's the _default_ theme of GTK+. It's the standard of GTK+ styling, I think. Despite Terminal is a native GTK+ app, why do you leave the "conflict" with GTK's  default? :)
