### ISSUE TITLE
CSD is thicker than other elementary OS Apps

### ISSUE THREAD

**Issue by quequotion** [elementary/terminal#270]
Terminal's CSD is [looking a little overweight](https://postimg.cc/image/sa05zqn3b/) compared to other elementary OS apps.

Also noted by 0xBE7ABEEF on [reddit](https://www.reddit.com/r/unixporn/comments/8rrchi/gnome_unobtrusive_desktop/e0tjed0/)

**Comment by cassidyjames** [comment]
It looks like you're using a non-elementary stylesheet. The elementary stylesheet supports a `.default-decoration` class which styles the headerbar more like a titlebar. The stylesheet you're using appears to not support that.

**Comment by quequotion** [comment]
True, I'm using Adwaita. Is the stylesheet the only way to do this? Not that I mind copying it over from elementary's theme, but just to ask if it is _possible_ to change the width of the CSD on Terminal's end.

I kind of suspected the reason was that Terminal shows a static title, rather than an entry form (like epiphany, files, etc).

**Comment by danrabbit** [comment]
@quequotion Yes this is totally dependent on the stylesheet. None of the elements in the headerbar have any additional margin. The padding is being assigned here by Adwaita
