### ISSUE TITLE
Terminal doesn't get focused on after launch using slingshot search [$5]

### ISSUE THREAD

**Issue by uncertainquark** [elementary/terminal#281]
To reproduce:
Have a background application open (say Files). Open slingshot menu and then search and launch terminal. The terminal won't be take over the focus. 

![screenshot from 2018-07-08 21-30-54](https://user-images.githubusercontent.com/22585732/42421644-7c0225a8-82f6-11e8-9eaa-207ad3a597eb.png)

**Comment by LievenHanssen** [comment]
I was plagued by the same issue and made [a quick video](https://youtu.be/oH6qSFPm5cM) to show how we are affected by it.

**Comment by daquinons** [comment]
Yes!! That video is a perfect explanation, @LievenHanssen. I noticed this bug since Loki. 

Another thing: if you open Terminal using win+T it always gets focus, so I simply stop opening it with slingshot.
