### ISSUE TITLE
new release for VTE fix

### ISSUE THREAD

**Issue by CameronNemo** [elementary/terminal#285]
Hi all (and cody),

I know it is in the middle of the Juno release but I would appreciate a 0.5.1 for this package which includes this fix: https://github.com/elementary/terminal/commit/8a87b497f6d64c7a7c1ce2bcec176d467976faf6

I'm trying to update/upload some of the elementary packages in void and this is a blocker. I imagine it affects other rolling distros like Gentoo and Arch as well.

**Comment by codygarver** [comment]
Closed by c690a5d
