### ISSUE TITLE
Paste Warning Pastes on Escape

### ISSUE THREAD

**Issue by cassidyjames** [elementary/terminal#293]
We should only allow the paste if the user clicks the "Paste Anyway" button. Right now hitting escape also pastes.

**Comment by Blast-City** [comment]
Hi.

Also the tick box to not show the message again is focused so it's impossible to select cancel or paste.

**Comment by cassidyjames** [comment]
@Blast-City first, that's not directly related to this, so would probably deserve its own issue being opened. Second, you can tab between controls, just like anywhere else. Is that not working for you?

**Comment by Blast-City** [comment]
> @Blast-City first, that's not directly related to this, so would probably deserve its own issue being opened. Second, you can tab between controls, just like anywhere else. Is that not working for you?

Hi.

Tab works and pressing down as well, but i don't think that is the normal behaviour, is it?

If it isn't I'll post an issue.

Thanks.

**Comment by cassidyjames** [comment]
@Blast-City that's standard GTK behavior. Is your issue just that the checkbox is focused instead of one of the buttons?

**Comment by Blast-City** [comment]
> @Blast-City that's standard GTK behavior. Is your issue just that the checkbox is focused instead of one of the buttons?

Yes. I think that the "Don't Paste" button should be focused. When the dialog appears, if you press enter it shouldn't paste the command.
If you want to paste the command you should press right and then enter.
Esc should quit the dialog without pasting the command.
