### ISSUE TITLE
Feature request: Display available shortcuts

### ISSUE THREAD

**Issue by linkert** [elementary/terminal#310]
~~Files, Code and pretty much any non-vim-inspired software all use these two shortcuts for opening a new tab and closing tabs/windows. Why is this not the case for the terminal in eOS? Any alternative shortcuts available that I'm not aware of?~~

After discussion and help for the folks down bellow this feature request has now developed into an more generall issue regarding all the hidden shortcuts available to the included elementary apps. 
My suggestion is to build upon the existing elementaryOS Shortcut Viewer. I remember an application for OS X called [CheatSheet](https://www.cheatsheetapp.com/CheatSheet/). It's just like the elementaryOS Shortcut Viewer with the main difference that it displays all shortcuts available for the current active application with the a press of a keyboard shortcut. Looks just like elementaryOS Shortcut Viewer (any other name for it?), minimal yet very functional and intuitive.

**Comment by linkert** [comment]
> Ctrl+W is a default shell shortcut to remove words

Ok
Would be lovely to have access to any way of changing that as it is not the way anything else works. Let the end user modify shortcuts to their liking.

**Comment by ryonakano** [comment]
> Any alternative shortcuts available that I'm not aware of?

You can open a new tab with `Ctrl+Shift+T` and close current tab with `Ctrl+Shift+W`

**Comment by linkert** [comment]
> > Any alternative shortcuts available that I'm not aware of?
> 
> You can open a new tab with `Ctrl+Shift+T` and close current tab with `Ctrl+Shift+W`
Thank you! Works great - how did you find that out? I can't find anywhere to see shortcuts available for the terminal nor most other elementary projects either.

**Comment by ryonakano** [comment]
@linkert I'm sorry but I don't remember how…

**Comment by ryonakano** [comment]
Related issues to this issue:
https://github.com/elementary/granite/issues/228
https://github.com/elementary/shortcut-overlay/issues/53

**Comment by ryonakano** [comment]
Fixed in #387

**Comment by parnold-x** [comment]
> > > Any alternative shortcuts available that I'm not aware of?
> > 
> > 
> > You can open a new tab with `Ctrl+Shift+T` and close current tab with `Ctrl+Shift+W`
> 
> Thank you! Works great - how did you find that out? I can't find anywhere to see shortcuts available for the terminal nor most other elementary projects either.

https://elementaryos.stackexchange.com/questions/981/list-of-keyboard-shortcuts-for-terminal/983#983

**Comment by jeremypw** [comment]
Some shortcuts now appear in the terminal context menu. Others appear in the tooltips that appear in the AppMenu.  However, the tab context menu has not got them yet.  This will no doubt be done in future.

**Comment by ryonakano** [comment]
@jeremypw Maybe the shortcuts for the tab context menu would be addressed not here but in the Granite's DynamicNotebook since Terminal uses it?

**Comment by jeremypw** [comment]
@ryonakano Hmm, looks like you are right.  But it would be difficult to specify a particular shortcut in Granite as that would apply globally. Moreover the tab menuitems are private to the Notebook so the app cannot add a shortcut indication to their labels even it the app implements such shortcuts. :-(

I guess the first step would be to expose the tab menu and its items in Granite.DynamicNotebook at least to a sufficient degree to allow shortcuts to be added.
