### ISSUE TITLE
Include keyboard shortcuts in tooltips

### ISSUE THREAD

**Issue by peteruithoven** [elementary/terminal#320]

**Comment by peteruithoven** [comment]
Looks like this was partly fixed by: https://github.com/elementary/terminal/pull/318
For the tabs related shortcuts we have to wait for something like: https://github.com/elementary/granite/pull/236

**Comment by danrabbit** [comment]
Gonna close this since as far as the Terminal codebase is concerned, this is solved. Changes to granite are out of scope for this repo's tracker
