### ISSUE TITLE
Messy auto-indentation on yml files

### ISSUE THREAD

**Issue by elavaud** [elementary/terminal#326]
Quite often when I vim to change a yml file, the terminal auto-update the indentation of the file (and actually messes it up).

I am on Juno with Terminal 5.3.2

**Comment by CameronNemo** [comment]
this is more likely to do with the editor and the configuration it uses rather than the terminal emulator. please test with another terminal emulator (e.g. gnome-terminal) to verify if this problem is specific to elementary terminal.

**Comment by elavaud** [comment]
Indeed, same issue with gnome-terminal. 
In case somebody has the issue, I solved it by modifying the vim configuration. I created a vimrc file for my user (was not existing before):
`vim ~/.vimrc`
And set the indentation to off inside the file:
```
if has("autocmd")
  filetype plugin indent off
endif
```
