### ISSUE TITLE
Opening Terminal from Open With -> Files results in bad PS1 and other issues

### ISSUE THREAD

**Issue by BNolet** [elementary/terminal#329]
When using Files' Open With -> Terminal the PS1 results in `${debian_chroot:+($debian_chroot)}\u@\h:\w\$` whereas default is `\[\e]0;$(print_title)\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$`

What's more is that the text seems to be all smushed together. Not sure if that's a result of the PS1 change but here's a screenshot:
![image](https://user-images.githubusercontent.com/10198484/49320063-ca0b2080-f4cd-11e8-876f-e09490e566f6.png)

Steps to reproduce:
1. Have no terminal windows open
2. From Files, use the context menu to perform Open With -> Terminal
3. Cringe in disgust

**Comment by janxkoci** [comment]
I don't see this behaviour. However when I open terminal this way, I always have extra tab there with Home folder. But that's another issue.

**Comment by BNolet** [comment]
Okay, I'm closing this. It's not happening anymore. Wtf. I've rebooted since, so that probably fixed whatever happened.
