### ISSUE TITLE
Ctrl-X does not work in files

### ISSUE THREAD

**Issue by cmburg** [elementary/terminal#344]
I am using a lenovo T430/T400 running juno and have the issue that the cut-command does not work (even on 0.4, unsure if even on older versions). When I rightclick and select "cut" the file gets cut as desired. No problems with that combination for cutting text.

**Comment by jeremypw** [comment]
When you say ".. does not work in files" do you mean "... does not work in Files (the file manager)"?  If so this is not the correct project. You should raise the issue in https://github.com/elementary/files/issues.

There is an existing similar issue regarding Dvorak keyboards so do not duplicate.  You will need to specify your keyboard layout and locale.

**Comment by cmburg** [comment]
Thank you for your answer. Yes, I mean the file-manager. Cutting text works fine.

My locale is DE for Germany and my keyboard layout is both the normal German one and Neo2.

Is it possible to link to the file manager from here or should I create a new issue? Didn't see this was issued to the terminal.
