### ISSUE TITLE
Atom text editor does not show up after launch (mostly)

### ISSUE THREAD

**Issue by cmburg** [elementary/terminal#345]
I am running atom (1.33) in juno on both lenovo t400/t430 and sometimes (most of the time) the window is not displayed. Pressing ctrl-w for a windows overview I can see atom has been launched but only the window decoration is rendered. When you have no window open and do not use the overview the only hint atom has started is that wingpanel became black (as for all maximised windows). Moving the poiter where the windows titlebar should be and click the left mouse button you see the "grabbing handle" and after dragging the window gets redrawn and appears as desired. 

Normal desktop with non-maximised window:
![arbeitsflache 1_020](https://user-images.githubusercontent.com/18635557/50204441-1b882c00-0365-11e9-964e-47d12c15459b.png)

The same desktop after launch. Wingpanel blacked out/ dock hidden:
![arbeitsflache 1_022](https://user-images.githubusercontent.com/18635557/50204832-6a829100-0366-11e9-89cd-845725e383e5.png)

Window overview:
![arbeitsflache 1_019](https://user-images.githubusercontent.com/18635557/50204440-1b882c00-0365-11e9-8ad7-54605b8ae9f3.png)

**Comment by jeremypw** [comment]
I do not think this is a Terminal issue.  It is likely to be a Window Manager (Gala) issue, so please raise at
https://github.com/elementary/gala/issues.  Thanks.
