### ISSUE TITLE
tab view like io.elementary.code

### ISSUE THREAD

**Issue by torikulhabib** [elementary/terminal#350]
tab view like io.elementary.code

**Comment by cassidyjames** [comment]
Could you provide more details? I'm not sure what you're asking for here.

**Comment by torikulhabib** [comment]
i hope tab terminal like code
![screenshot from 2019-03-01 05-40-15](https://user-images.githubusercontent.com/26135527/53603586-84e9ae00-3be4-11e9-9f45-feb55881f8a5.png)

**Comment by cassidyjames** [comment]
@torikulhabib do you mean the visual style? Because currently Terminal and Code use the exact same Granite widget to draw tabs.

**Comment by johnyoonh** [comment]
Maybe you should specify what you like about it. If you are like me, maybe you like that the currently selected tab is more nuanced, making it more easy to identify the tab.

**Comment by cassidyjames** [comment]
I'm closing this as incomplete, as it's still not clear what's being asked for. Both apps use the exact same Granite tabs widget.
