### ISSUE TITLE
Strage middle mouse tab behavior

### ISSUE THREAD

**Issue by AtjonTV** [elementary/terminal#353]
Sometimes when trying to close a tab using the Middle Mouse button on the tab, it creates a new tab instead of closing the one you hover on.

I noticed this a bit ago. I cant remember if I saw the same behavior on Loki.

I dont know if and where the Terminal has some logs that may tell what is going on, when I get that info I will be posing the log.

**Comment by cassidyjames** [comment]
I think this is a Granite issue that was resolved. https://github.com/elementary/granite/issues/294
