### ISSUE TITLE
Duplicate tab keyboard shortcut?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/terminal#354]
It's possible to duplicate a tab by right clicking the tab and selecting Duplicate. I'd love to be able to do this with a keyboard shortcut. 
Existing keyboard shortcuts:
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>N</kbd>: Open new window
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>T</kbd>: Open new tab
Maybe we can introduce the following?
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>D</kbd>: Duplicate tab

In browsers like Chrome and Firefox the only way to do this with the keyboard is by doing:
1. <kbd>Alt</kbd> + <kbd>D</kbd> or <kbd>Ctrl</kbd> + <kbd>L</kbd> (focus url bar)
2. <kbd>Alt</kbd> + <kbd>Enter</kbd> (open in new tab)
While this might be interesting for Files, we don't have a url bar in Terminal.

Are there other applications with tabs we can draw inspiration from?

**Update:** Double clicking on an existing tab will also open a duplicate tab.

**Comment by jeremypw** [comment]
Code looks OK.  @elementary/ux - is `<Ctrl><Shift>D` OK for the shortcut?

**Comment by cassidyjames** [comment]
@jeremypw hm, it looks like all major browsers use Ctrl+D to bookmark (why, I have no idea). So I think that could run into conflicts in other apps if we wanted to keep the same convention here.

**Comment by jeremypw** [comment]
I guess so. if they do not check the `<Shift>` key.  Do you have a suggested alternative or is it not a worthwhile idea at all?

**Comment by jeremypw** [comment]
Actually, as this is a terminal, without bookmarking facilities I do not think conflict with browsers is an issue.  Other apps use `<Ctrl>D` for their own purposes e.g. Code uses it for duplicating the current line or selection.  However, at least some terminals close the current tab (or the app if one tab) with `<Ctrl><Shift>D` as well as `<Ctrl><Shift>W`, so another shortcut may be advisable anyway.

**Comment by jtrees** [comment]
I am also interested in this feature. And given the other shortcuts I think `<Ctrl><Shift>D` is most intuitive.

**Comment by jeremypw** [comment]
Is there any reason why the existing `<Ctrl><Shift>t` shortcut could not simply default to opening at the same location as the currently active tab?  The changes are that if opened at the home directory the user will navigate elsewhere anyway.

**Comment by jeremypw** [comment]
If the home directory is a particularly desirable location, then we could add a shortcut to navigate there (Files uses `<Alt>Home`)

**Comment by peteruithoven** [comment]
Actually as far as I know typing `cd` should suffice.

**Comment by jtrees** [comment]
> Is there any reason why the existing `<Ctrl><Shift>t` shortcut could not simply default to opening at the same location as the currently active tab? The changes are that if opened at the home directory the user will navigate elsewhere anyway.

Technically that could work but I find it to be a bit inconsistent. Opening a new tab in Code doesn't duplicate the current document, opening a new tab in Files doesn't open a tab in the same folder and so on.

**Comment by jeremypw** [comment]
@jtrees I think that consistency can be pushed too far - after all these three apps are dealing with completely different things.  If you open a new tab in Code you are more likely to be wanting to start a new document.  In Terminal if you open a new tab you want to start a new shell but there is no particular reason to start at a particular place.  In Files it could be argued that your favorite folders are most likely to be in your home folder so that is a good starting point.

I take your point though - I was just trying to avoid the problem of what the shortcut should be.
