### ISSUE TITLE
Auto-hide the mouse cursor when is over the window area and a key is pressed.

### ISSUE THREAD

**Issue by Blast-City** [elementary/terminal#355]
I'm sorry if this issue is a duplicate.

On Ubuntu terminal and on VLC there is this feature that auto-hides the mouse when the mouse is over the window area and a key is pressed.

What if elementary Terminal had a similar function?

If the mouse cursor was over the window it would auto-hide when a key was pressed.

This works particularly well when the terminal is in fullscreen mode.

**Comment by cassidyjames** [comment]
@Blast-City interesting suggestion! This is actually a native GTK feature for entries, I wonder why it's not baked into libvte (the terminal emulator library). I think it's worth pursuing though!

**Comment by egmontkob** [comment]
>  wonder why it's not baked into libvte

???

https://developer.gnome.org/vte/0.38/VteTerminal.html#vte-terminal-set-mouse-autohide

**Comment by cassidyjames** [comment]
@egmontkob well then, that's embarrassing. In that case, this should be a one-line or so fix in Terminal to set that property.
