### ISSUE TITLE
modify base tab bar scss for flexible tab width

### ISSUE THREAD

**Issue by brunnels** [elementary/terminal#359]
I think it's in the ng tabs scss but you can have a large tab width with single tab and it auto shrinks as more are added using this css override:

`css: '.tab-bar[_ngcontent-c0] > .tabs[_ngcontent-c0] { flex: 1 1 auto !important; }'`

**Comment by danrabbit** [comment]
I'm not sure it's exactly clear what this issue report is trying to describe. Can you try to describe the problem in a little more detail?

**Comment by brunnels** [comment]
Sorry should have specified enchantment request. It’s just nice to have the
wider tab to show the full path in the title.

**Comment by danrabbit** [comment]
It sounds like this is a request for full-width tabs. Going to close this as "Out of scope" since tab width is handled in Granite and not per-app
