### ISSUE TITLE
Alt + up keybinding

### ISSUE THREAD

**Issue by Julioevm** [elementary/terminal#362]
Is Alt + Up a keybind on the Elementary Terminal? I can't see it doing anything, yet it is not working on tmux, so I must assume something else is intercepting the combination. I can only think it's some shortcut in the terminal itself that is not documented. Am I wrong?

**Comment by CameronNemo** [comment]
https://github.com/elementary/terminal/releases/tag/5.3.3

**Comment by Julioevm** [comment]
Yep, just saw the release notes. Cheers!
