### ISSUE TITLE
Terminal no longer quits with running process

### ISSUE THREAD

**Issue by Julioevm** [elementary/terminal#367]
After pressing the close button while a process is currently running you get a confirmation window to close the terminal. Well, for a couple of days now (Using Freya with up to date packages) it no longer closes.
It doesn't seem to matter what process is running, it wont close it, and  if you don't do it manually you cant close the terminal.

It does work without problems when closing tabs with processes running. And I'm not running the processes as root.

**Comment by muriloventuroso** [comment]
in Juno too...

**Comment by Angedestenebres** [comment]
I noticed the same issue.

The only way to close it in that case is to close all tabs with "running process".
If you have only one tab, in this case the terminal got closed :)
