### ISSUE TITLE
Dialog to quit terminal when a process is running doesn't quit terminal.

### ISSUE THREAD

**Issue by Blast-City** [elementary/terminal#372]
1- Open Terminal
2- Write `nano test` and press enter
3- Press Alt+F4 and press "Quit Terminal"

Result: The terminal doesn't quits. Dialog buttons and the Esc key cancel the "force quit".

P.S: I'm sorry if this is a duplicate issue.

**Comment by donadigo** [comment]
Already fixed in master: https://github.com/elementary/terminal/commit/7f160d9a4be5697f991fd4ea9eaa533cb9dd1a39. Closing.
