### ISSUE TITLE
Window state (position) restoration is partially broken

### ISSUE THREAD

**Issue by ludmiloff** [elementary/terminal#393]
Using latest v5.3.6 on Gnome 3.32 / Ubuntu 19.04 - window position is restored with slight offset by x,y. The offset is about 32px, not sure. The position is actually saved and read exact, only difference is that when the window is finally present it's position has an offset compared to the position when previously closed.

I've checked the code and tweaked a bit - moving `restore_saved_state (restore_pos) ` after `setup_ui ()` call fixes the problem. Also it is good to change Gtk.Window to Gtk.ApplicationWindow, though not related to the above;

Would glad to send a pull-request

**Comment by jeremypw** [comment]
Closing as this does not seem to be an issue on Odin.
