### ISSUE TITLE
Can't use options with io.elementary.terminal

### ISSUE THREAD

**Issue by devprabal** [elementary/terminal#395]
For example : 
` io.elementary.terminal -h `
 produces the following output 
>  [DEBUG 21:57:54.738715] Settings.vala:163: Loading settings from schema 'io.elementary.terminal.settings' Usage:   io.elementary.terminal [OPTION…]  

Why do I need this to work?  

I have to change "Terminal to launch console program" from ***xterm -T $TITLE -e*** to elementary's OS (Juno) ***io.elementary.terminal -e*** in CodeBlocks.
How do I fix this?

**Comment by jeremypw** [comment]
When I type `io.elementary.terminal -h` I get:
```
[DEBUG 09:27:15.303574] Settings.vala:163: Loading settings from schema 'io.elementary.terminal.settings'
Usage:
  io.elementary.terminal [OPTION…]

Application Options:
  -e, --execute=COMMAND           Run a program in terminal
  -h, --help                      Show help
  -w, --working-directory=DIR     Set shell working directory
  --display=DISPLAY               X display to use

```

The debug message is superfluous but does not indicate an error (it is coming from the Granite library not Terminal).  The options should all work, including -e.  Is the -e option not working for you?

**Comment by devprabal** [comment]
CodeBlocks has `xterm` as the default terminal. But it supports options to change to another terminal.

**With gnome-terminal** : 
`Executing: gnome-terminal -t test1 -x  /usr/bin/cb_console_runner LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. /home/devpogi/Documents/scratch-codes/learning-C++/test1/bin/Debug/test1  (in /home/devpogi/Documents/scratch-codes/learning-C++/test1/.)`

The above is the Build Log output. I can see that gnome-terminal has been called with -x (execute) command to execute whatever is after it.
This opens up the gnome-terminal and executes perfectly.
![Screenshot from 2019-08-23 01-26-34](https://user-images.githubusercontent.com/35391821/63545799-dcd6f100-c545-11e9-80cf-f98deb08e0d7.png)

**However, I want to achieve this in io.elementary.terminal too.**

So, in the CodeBlocks Settings->Environment->Terminal to launch console programs, I just have to change the line 
`gnome-terminal -t $TITLE -x `
to 
`io.elementary.terminal -e`
and it should work fine **but it produces no output on any of the two tabs that it opens in the terminal window**

The build log is this -
`Executing: io.elementary.terminal -e /usr/bin/cb_console_runner LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. /home/devpogi/Documents/scratch-codes/learning-C++/test1/bin/Debug/test1  (in /home/devpogi/Documents/scratch-codes/learning-C++/test1/.)`
![Screenshot from 2019-08-23 01-27-39](https://user-images.githubusercontent.com/35391821/63545775-cd57a800-c545-11e9-8274-2bf1a3284c41.png)

**Comment by jeremypw** [comment]
Try putting everything after the -e flag in quotes.

**Comment by devprabal** [comment]
First,
I cannot put quotes because I don't provide it the **thing** which is after -e flag. That is done by CodeBlocks. I have to just choose a terminal in which to show output. There is no option of elementary terminal in the selection of terminals (but there is gnome-terminal option).
So following the structure of command provided by gnome-terminal, if I put the io.elementary.terminal -e then it should work. But it doesn't.
Second,
 I have manually tried doing that - putting things in quote. Still it doesn't work.

**Comment by jeremypw** [comment]
OK, thanks for letting me know. I'll look more closely why the -e flag is not working in this case. Maybe we need to implement a -x flag that behaves like gnome-terminal.

**Comment by jeremypw** [comment]
What exactly is being passed to io.elementary.terminal after the -e flag? Is it the whole of 
```
/usr/bin/cb_console_runner LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. /home/devpogi/Documents/scratch-codes/learning-C++/test1/bin/Debug/test1 (in /home/devpogi/Documents/scratch-codes/learning-C++/test1/.)
```

**Comment by jeremypw** [comment]
@devprabal I have just push a PR that may fix your issue.  If you are able to download, build and test it I would be grateful.  You would need to use the `-x` flag - the same as gnome-terminal.

**Comment by devprabal** [comment]
> What exactly is being passed to io.elementary.terminal after the -e flag? Is it the whole of
> 
> ```
> /usr/bin/cb_console_runner LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. /home/devpogi/Documents/scratch-codes/learning-C++/test1/bin/Debug/test1 (in /home/devpogi/Documents/scratch-codes/learning-C++/test1/.)
> ```

I guess this is all that is being passed to the flag
 `/usr/bin/cb_console_runner LD_LIBRARY_PATH=$LD_LIBRARY_PATH:. /home/devpogi/Documents/scratch-codes/learning-C++/test1/bin/Debug/test1`~~(in /home/devpogi/Documents/scratch-codes/learning-C++/test1/.)~~

---

I downloaded the source code and changed the files where you made changes and then built it and installed it. **It solves the problem.** Thanks a lot!
Attaching screenshot and log files
[meson-log.txt](https://pastebin.com/PmnTJEf4)
[testlog.txt](https://pastebin.com/3M7A5uDS)
![Screenshot from 2019-08-24 11-04-42](https://user-images.githubusercontent.com/35391821/63633142-b659a880-c660-11e9-8222-bcb87e9e7e9d.png)

**Comment by jeremypw** [comment]
Great! Thanks for letting us know :-)

**Comment by jmgibson1981** [comment]
I know this is marked as completed but one thing remains. Add the man page entry for the -x flag. It is not there as of today. I googled and found this issue.

**Comment by danirabbit** [comment]
@jmgibson1981 can you open a new issue report to describe the problem you're seeing please? Want to make sure that doesn't get lost under a closed report

**Comment by jmgibson1981** [comment]
Opened here - https://github.com/elementary/terminal/issues/728
