### ISSUE TITLE
"Copy Last Output" ignores first line(command) if sudo used and password entry required.

### ISSUE THREAD

**Issue by queeup** [elementary/terminal#396]
If sudo used and password prompt appears, first line of the output (the command used) ignored by "Copy Last Output" menu option.

Reproduce:
```
sudo ls
```
then try to copy and past output.

**Comment by jeremypw** [comment]
I can only reproduce this if there is a password entry line.  The password entry line is copied but not the command. Subsequent sudo commands (without password entry) are copied correctly.

There is a known limitation that multi-line commands are not fully copied (only the last line is copied). It looks like the password entry is being regarded as part of the command.
