### ISSUE TITLE
Middle click paste and copy is (still) broken

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/terminal#400]
I've been tracing the issues related to this problem that affects Terminal and apparently other apps as well, for 2 years now:

* _Oct 2017_: Middle click copy paste logic is broken #150 (terminal) -> **closed** by [#151](https://github.com/elementary/terminal/pull/151)
* _Jul 2018_, Middle click to paste setting is broken [#47](https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/47) (switchboard-plug-mouse-touchpad) -> **closed** by [#46](https://github.com/elementary/switchboard-plug-mouse-touchpad/pull/46)
* _Sep 2018_: Middle click paste toggle doesn't seem to work [#40](https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/40) (switchboard-plug-mouse-touchpad) -> **closed** as duplicate of the above issue
* _Oct 2018_: Middle click paste and copy #302 (terminal) -> **closed** as duplicate of the above issue

**All** the issues are closed but the problem remains. Is this being tracked in some other still open issue? If not, why were all the issues closed?

**Comment by jeremypw** [comment]
It seems that Code honours the setting in the mouse-touchpad plug but Terminal (and some non-elementary apps) does not.  Terminal always pastes selection on middle-click regardless of settings.  Is that what you mean by "broken"?

**Comment by Gabriel-p** [comment]
> Terminal always pastes selection on middle-click regardless of settings

No, it does not. This is the issue I'm talking about. Middle click pasting does not work in Terminal.

**Comment by Gabriel-p** [comment]
> Terminal always pastes selection on middle-click regardless of settings

I just tried enabling middle-click pasting in the settings and **now** it works. It did not occur to me to try that before, because it used to always work, as you said.

If I disable that option in settings, middle-clicking does not paste in Terminal.

**Comment by Gabriel-p** [comment]
I'm closing this issue because, as I said above, middle click pasting works in Terminal if I enable the option in the settings.
