### ISSUE TITLE
Close tab(c-w), open tab(c-t) and new window(c-n)

### ISSUE THREAD

**Issue by neauoire** [elementary/terminal#419]
I'm just wondering why these are not implemented? Also, kind of curious why `c-t` opens a new window instead of a new tab?

**Comment by danrabbit** [comment]
Terminal keyboard shortcuts also include `Shift` because standard shortcuts interfere with BASH's shortcuts. So to open a new Tab you can use `Ctrl` + `Shift` + `T`, close a tab with `Ctrl` + `Shift` + `W`, and open a new window with `Ctrl` + `Shift` + `N`

**Comment by neauoire** [comment]
Thanks a lot :)
