### ISSUE TITLE
Implement drag-drop tabs between terminal windows

### ISSUE THREAD

**Issue by jeremypw** [elementary/terminal#426]
I have searched open and closed issues for duplicates.

## Feature
It is possible to create a new terminal window by dragging a tab and dropping onto desktop.
However dropping a tab onto the tab-bar of another terminal window does not transfer the tab to that window. Files and Code windows have this feature, so for consistency Terminal should behave similarly.

**Existing work**
This feature exists in Files and Code.

**Comment by MHebes** [comment]
I think this works, no? Maybe I'm misunderstanding what you're asking, but you can definitely drag a tab from one terminal window to another.

**Comment by jeremypw** [comment]
Yes - either I was dropping in the wrong place or something has changed recently.  I note that if you try and line up the dragged tab icon with the tab bar it is easy to drop it on the header bar instead (creating a new window). You have to be careful to drop the top left corner of the drag icon onto the tab bar,
