### ISSUE TITLE
Feature: allow to close terminal tab with Ctrl + F4

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/terminal#428]
Many modern browsers allow to close tabs with the keyboard shortcut Ctrl+F4

I'd lilke to be able to close the currently open terminal tab with Ctrl+F4 (but the shortcut should be configurable through gsettings)

**Comment by cassidyjames** [comment]
I'm inclined to close this, as we use Ctrl+W consistently throughout the OS, and Terminal follows the convention of Ctrl+Shift+W to avoid conflicting with command-line app shortcuts. Ctrl+F4 does not work in any other app we ship in elementary OS.

**Comment by CodingSpiderFox** [comment]
How about making it configurable?

**Comment by cassidyjames** [comment]
@CodingSpiderFox that also goes against our [design guidelines](https://elementary.io/docs/human-interface-guidelines#accessible-configuration). This would imply adding settings to every single app that uses tabs in elementary OS, for a shortcut that is legacy from other platforms/apps and has never been supported by our apps. I can't really see how that is worthwhile to implement, add complexity, and support in perpetuity.

**Comment by CodingSpiderFox** [comment]
Could you at least give me a hint on how I could implement a keyboard shortcut for this for myself on my own fork of elementary terminal? I struggle a lot with vala because of the lack of a proper IDE.

**Comment by cassidyjames** [comment]
@CodingSpiderFox you'll want to modify this line:

https://github.com/elementary/terminal/blob/bbbdc0b160d45f4d711230b7ce86e752495daa37/src/MainWindow.vala#L140

**Comment by CodingSpiderFox** [comment]
Thansk a lot !
