### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by aggalex** [elementary/terminal#454]
## Prerequisites
- I have updated elementary.

## Describe the bug
The terminal app won't start up. When starting it from the 'code' terminal, I get
`io.elementary.terminal: symbol lookup error: io.elementary.terminal: undefined symbol: granite_accel_label_new_from_action_name`

### To Reproduce
1. Update (?)
2. Click to open terminal
3. Cursor goes into loading mode, the window is nowhere to be found
#### or
2. Go to code
3. Open the terminal plugin
4. run `io.elementary.terminal`
5. get `io.elementary.terminal: symbol lookup error: io.elementary.terminal: undefined symbol: granite_accel_label_new_from_action_name`

### Expected behavior
Should have opened normally

## Platform Information
- elementary OS 5.1 Hera
- Linux 4.15.0-74-generic
- HP ELITEBOOK-8440P
- Dual-Core Intel® Core™ i5 CPU       M 520  @ 2.40GHz
- Intel Corporation Core Processor Integrated Graphics...
- 3,8 GB memory
- 117,1 GB storage (SATA SSD)

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by jeremypw** [comment]
Do you have the latest version of Granite installed? (v 5.3.0)  This is the one with the new AccelLabel widget.

**Comment by jeremypw** [comment]
Just tried this on an unmodified, fully updated stable install and did not experience this issue.

**Comment by danrabbit** [comment]
I'm going to close this since packaging will now require that the correct version of Granite is installed. The update should land within the next 24 hours :)

**Comment by aggalex** [comment]
Still, same issue. Not resolved

**Comment by jeremypw** [comment]
Could you indicate the installed versions of terminal and granite? Use synaptic or the commandline.
Check there are no system files installed in `/usr/local`.   I assume you have "switched off and on again" ;-)

**Comment by aggalex** [comment]
The installed version is 5.3.0. 

> Check there are no system files installed in /usr/local

What do you mean by that

**Comment by jeremypw** [comment]
Below the folder `/usr/local` there should be very little, if anything, installed in `/usr/local/bin` or `/usr/local/lib`.  This is only likely to happen if you have been compiling and installing from source or possibly if you have installed software from some 3rd party ppa.  Its just that if there were an old version installed here, will run in preference to the version installed by elementary.

If that is not the case then I am puzzled as to what is causing your problem.  I suspect t is not commonly experienced as it would be likely there would be other reports of a fatal bug like this.

**Comment by jeremypw** [comment]
You could try reinstalling granite 5.3.0 using synaptic but be careful not to uninstall it else you will break the system. Do this at your own risk.

**Comment by aggalex** [comment]
I tried `sudo apt install --reinstall libgranite5 libgranite-common libgranite-dev` but to no avail. My `/usr/local` folder doesn't have anything related to granite in it. Perhaps reinstalling must be my only option...

**Comment by jeremypw** [comment]
Did you try reinstalling Terminal as well, just in case?  Otherwise, I am sorry not to be able to diagnose you problem :-(

**Comment by aggalex** [comment]
Yes I have. I think also found this issue on another piece of software, but I cannot remember which one...

**Comment by aggalex** [comment]
So the bug reappeared in wingpanel, when I click on the session icon, it crashes.
`wingpanel: symbol lookup error: /usr/lib/x86_64-linux-gnu/wingpanel/libsession.so: undefined symbol: granite_accel_label_new`

Seems like the apps don't take the updated version on granite...

**Comment by jeremypw** [comment]
Strange. It really does sound like there is an old version of granite lurking somewhere on your system that is taking precedence over the newly installed version and to which the apps are still linking.

**Comment by aggalex** [comment]
Now that I think of it, I do think I built a granite version to make a split window widget. The `libgranite.so.5.3.0` library (at `/usr/lib/x86_64-linux-gnu`) has all the appropriate symbols:

    alex@AlexPC:/usr/lib/x86_64-linux-gnu$ nm -gD libgranite.so.5.3.0 | grep accel
    0000000000034fa0 T granite_accel_label_construct
    0000000000034ff0 T granite_accel_label_construct_from_action_name
    0000000000035110 T granite_accel_label_get_accel_string
    0000000000035060 T granite_accel_label_get_action_name
    0000000000035500 T granite_accel_label_get_label
    0000000000035530 T granite_accel_label_get_type
    00000000000355a0 T granite_accel_label_new
    00000000000355d0 T granite_accel_label_new_from_action_name
    0000000000035140 T granite_accel_label_set_accel_string
    0000000000035090 T granite_accel_label_set_action_name
    000000000005ddc0 T granite_accel_to_string
    000000000005e2e0 T granite_markup_accel_tooltip
                     U gtk_accelerator_get_default_mod_mask
                     U gtk_accelerator_get_label
                     U gtk_accelerator_parse
                     U gtk_application_get_accels_for_action

Including the ones that wingpanel (`granite_accel_label_new`) and terminal (`granite_accel_label_new_from_action_name`) need. Yet they cannot find it. How do I find the path of the library the app links with?

**Comment by aggalex** [comment]
NVM, with some bash-fu I fixed it...

    ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012 | sed 's/SEARCH_DIR("=//g' | sed 's/")//g' > paths.txt
    for i in `cat paths.txt`; do echo -e "\033[1;31m-- at $i\033[0m"; ls "$i" | grep granite ; done

and I got

    -- at /usr/local/lib/x86_64-linux-gnu
    libgranite.so
    libgranite.so.5
    libgranite.so.5.2.4
    -- at /lib/x86_64-linux-gnu
    -- at /usr/lib/x86_64-linux-gnu
    libgranite.so
    libgranite.so.5
    libgranite.so.5.3.0
    -- at /usr/lib/x86_64-linux-gnu64
    ls: cannot access '/usr/lib/x86_64-linux-gnu64': No such file or directory
    -- at /usr/local/lib64
    ls: cannot access '/usr/local/lib64': No such file or directory
    -- at /lib64
    -- at /usr/lib64
    ls: cannot access '/usr/lib64': No such file or directory
    -- at /usr/local/lib
    -- at /lib
    -- at /usr/lib
    -- at /usr/x86_64-linux-gnu/lib64
    ls: cannot access '/usr/x86_64-linux-gnu/lib64': No such file or directory
    -- at /usr/x86_64-linux-gnu/lib
    ls: cannot access '/usr/x86_64-linux-gnu/lib': No such file or directory

There. Silly me missed the older version of granite at `/usr/local/lib/x86_64-linux-gnu`. After I removed it, everything ran perfectly. Thank you, and sorry for taking your precious time for such a small thing... Have a nice day!

**Comment by jeremypw** [comment]
No problem - glad to help.
