### ISSUE TITLE
New tab at home every time Terminal is launched

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/terminal#457]
## Prerequisites
- [x ] I have searched open and closed issues for duplicates.

## Describe the bug
Launching the Terminal app results in my old tabs in their correct positions, but also a new tab at the left located at `/home/`.

### To Reproduce
Open Terminal that has other tabs already opened. 

### Expected behavior
No new tabs should be created?

## Platform Information
![Captura de pantalla de 2020-01-10 09-01-30](https://user-images.githubusercontent.com/6054951/72173866-3c2f8380-33b7-11ea-97f0-63f44edd8efb.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
Perhaps this is new behavior?

**Comment by zimnyd** [comment]
Is the same as https://github.com/elementary/terminal/issues/441

**Comment by jeremypw** [comment]
Closing as a fix has been merged with master.
