### ISSUE TITLE
How can I get deb package? Reinstall it.

### ISSUE THREAD

**Issue by dobma** [elementary/terminal#464]
5.5.0 and 5.5.1 version of this terminal is terrible, so I want to reinstall 5.4.0 version. So can anybody tell me how to download the deb. And there is no 5.4.0 package [ppa](http://ppa.launchpad.net/elementary-os/stable/ubuntu/pool/main/p/pantheon-terminal/). Thanks.

**Comment by tintou** [comment]
We don't support installing previous versions, your only luck is to download, build and install the application from here https://github.com/elementary/terminal/releases/tag/5.4.0

**Comment by jeremypw** [comment]
@dobma  As you do not specify any particular problem(s) I assume that these have already been reported since the these releases?
