### ISSUE TITLE
💡: Access other tab info when tabs hidden

### ISSUE THREAD

**Issue by yozachar** [elementary/terminal#493]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature Request
When terminal tabs are hidden it's not possible to tell which terminal you want to switch to, quickly... so some kind of `hover-to-pop` indicator on the title bar will be useful.

**Comment by jeremypw** [comment]
What extra information should be shown? The headerbar already shows the current tab label.

**Comment by joe733** [comment]
>... which terminal you are in ...

Sorry
> ... which terminal you want to switch to ... (with <kbd>Alt</kbd>+<kbd>N</kbd>)

So something like [this @figma](https://www.figma.com/proto/Mct2vbGfTIWeWu1jNofzRq/elementary-OS-Terminal?node-id=2%3A2&scaling=contain) will be help full.

Just let the page load and hover over the `green-indicator` on the top-left corner.

The `green-indicator` can have other meaning: `git status` of the `cwd/pwd`.
```dart
green = working tree clean
yellow = modified objects
red = untracked objects
no_colour = not a git repository
```

**Comment by jeremypw** [comment]
OK, that is clearer now. I do not think the green indicator is a good choice as it has other uses, but some kind of headerbar widget to show a list of other available tabs makes sense when tabs are hidden.  Flagged for design team input.

**Comment by yozachar** [comment]
Closing, outdated.
