### ISSUE TITLE
Filename not readable when permissions are 777

### ISSUE THREAD

**Issue by rajkumaar23** [elementary/terminal#501]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The filenames are not at all readable when the permissions are 777 (applies to all the 3 themes provided)
![image](https://user-images.githubusercontent.com/37476886/78750727-75639980-798e-11ea-83a0-ebdd27c0833a.png)

### To Reproduce
1. Go to terminal
2. `chmod` one or two files to `777`
3. Do an `ls -a`
4. See the filenames which are with `777` being not readable.

### Expected behavior
The filenames should be displayed in a better color.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
You can temporarily turn off the coloration with `ll --color=none` but need to change the color palette of the terminal for a permanent fix.  This is initially set in the code but can be modified by changing the setting `io.elementary.terminal.settings.palette`  However, it is not obvious how to change it for the better manually. I agree that the color contrast for this combination is not great.  I assume it is the `ls` command that chooses which pair of colors to choose (blue on green) so it is never going to be very readable for color-blind people.

**Comment by jeremypw** [comment]
You can improve things by lightening the 3rd item in the palette (green) (e.g. :#99BB22) and darkening the 5th item (navy) (e.g. #2626d2).  Need design team to specify acceptable default colors for elementary.

**Comment by rajkumaar23** [comment]
@jeremypw Cool. Thanks for that. Just edited with `dconf-editor` and it looks better. 😁️

**Comment by dougabugg** [comment]
I ran into this issue as well, I tried changing the terminals theme from the gear icon menu, but it just changed the background, not the color of the text. This app is completely unusable for me.

**Comment by jeremypw** [comment]
see #418
