### ISSUE TITLE
Wrong focus on sudo paste warning dialog

### ISSUE THREAD

**Issue by justledbetter** [elementary/terminal#502]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When a user pastes a command containing "sudo" into the terminal window, the checkbox is selected by default instead of the highlighted main action button.

### To Reproduce
1. In any other window, type the string "sudo ls" and copy it.
2. Open Terminal (or close and re-open if using it previously)
3. Paste the string in the terminal window
4. In the popup dialog box, the checkbox is highlighted. Pressing *enter* or *space* toggles the checkbox, rather than approving the action.

### Screenshots or Screen Recordings
![Screenshot from 2020-04-10 16 47 34](https://user-images.githubusercontent.com/13354341/79022036-126b3180-7b4b-11ea-9f0d-eeaee893aecc.png)

### Expected behavior
The red button indicates that the default action of the dialog box is dangerous, but that accepting the action is the expected default behavior (similar to an "Ok" button in other dialog contexts).  It is meant to serve as a warning, rather than a failsafe protection measure.

## Platform Information
- OS: elementary OS
- OS Version: 5.1.3 Hera
- Huawei Matebook X
- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

## Additional context
Happy to debate whether or not this should be the default behavior - To me, the action this dialog box is asking for is "Press *enter* to accept or *esc* to cancel," as any other standard modal warning would do.

**Comment by cassidyjames** [comment]
We probably need to add guidance for these sorts of situations to the HIG and then make sure all our apps are following them. My inclincation is that a destructive action should never have default focus, even if it's in the primary position. But I see why that's a little awkward/unexpected.

Maybe instead we give the secondary (safe) action default focus, add that guidance to the HIG, and it will feel right if it's consistent within destructive action dialogs?

**Comment by justledbetter** [comment]
Having the <reject> button be the default focus would work, too.  Tab, Enter is one less keypress than Tab, Tab, Enter from my perspective.  :)

**Comment by danrabbit** [comment]
I agree that destructive actions should never have default focus and it makes sense to add that to the HIG

I think we didn’t put focus on the “cancel” action here so that people who press enter without reading wouldn’t accidentally close the dialog

**Comment by justledbetter** [comment]
OK if that's a design decision then I'm fine leaving it as-is.  Thanks for the quick clarification!
