### ISSUE TITLE
Unlike the Files app, closing the last tab exits Terminal.

### ISSUE THREAD

**Issue by Blast-City** [elementary/terminal#509]
1- Open terminal and make sure there is only one tab open.
2- Close the tab.

**Result:** Terminal exits.

From what I've read, Terminal is supposed to remain like Files and Epiphany (I guess).

P.S:I'm sorry if this have been brought before.

**Comment by jeremypw** [comment]
This has been discussed at length in Files - see https://github.com/elementary/files/issues/327. It is Files that is out of step with Terminal and web browsers like Epiphany in that it _doesnt_ close when the last tab is closed. It is more likely that Files will change to close when last tab is closed or at least provide a setting to do so.

**Comment by Blast-City** [comment]
> This has been discussed at length in Files - see [elementary/files#327](https://github.com/elementary/files/issues/327). It is Files that is out of step with Terminal and web browsers like Epiphany in that it _doesnt_ close when the last tab is closed. It is more likely that Files will change to close when last tab is closed or at least provide a setting to do so.

Thanks.

The only thing I've found was [this post on epiphany](https://gitlab.gnome.org/GNOME/epiphany/issues/80#note_271229) which, if I'm understanding correctly, seems to indicate otherwise.

I will close this then.

**Comment by jeremypw** [comment]
Yes, as I said - the issue is controversial.  Perhaps the only solution is to create a setting.
