### ISSUE TITLE
Better tab separation in dark theme

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/terminal#516]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
The tabs in the terminal are not clearly demarcated when in dark mode and when I have multiple tabs open from the same path, it is virtually impossible to see which tab I'm actually using even though there is an `x` that appears to close the tab.

![image](https://user-images.githubusercontent.com/46734097/83040612-aeb69e00-9ffc-11ea-9a9e-9543a2c0d800.png)

**Describe the solution you'd like**

A clearer demarcation between tabs should exist in the dark theme. One option could be highlighting the tab text in bold or higher font weight. Another solution could be increasing the shadow of the tab and increasing border weight to make it thicker.

**Existing work**

I know Atom highlights the tab text in dark mode which helps a lot. 
![image](https://user-images.githubusercontent.com/46734097/83042538-fdfdce00-9ffe-11ea-8bc6-a836554bf074.png)

**Comment by cassidyjames** [comment]
We're currently working on a rewrite of the system stylesheet, and this is the current notebook tab style for the dark style. We do have plans to continue to iterate and improve contrast overall in the dark style.

![Screenshot from 2020-05-27 10 59 31](https://user-images.githubusercontent.com/611168/83050032-2b4f7980-a009-11ea-9592-7085287e34aa.png)
