### ISSUE TITLE
Feature Request: Allow displaying graphics inline

### ISSUE THREAD

**Issue by dsancheznet** [elementary/terminal#518]
Several terminal emulators such as [Terminology](https://www.enlightenment.org/about-terminology.md) or [Kitty Terminal](https://sw.kovidgoyal.net/kitty/) or even xterm have the ability to display images and PDF inline ( small preview thumbnails or the complete image ). There are utilities that allow the display of such images in xterm as well, like [lsix](https://github.com/hackerb9/lsix), but
they do not work under elementary's Terminal.

Request the possibility to view images inline with elementary's native Terminal.

Best regards
D.Sánchez

**Comment by cassidyjames** [comment]
I don't think this is something we could directly control, as we use the libvte for the Terminal contents. Someone feel free to correct me if I'm wrong, but I think that it would need to be raised on the [GNOME GitLab](https://gitlab.gnome.org/GNOME/vte).
