### ISSUE TITLE
Functionality improvements are needed.

### ISSUE THREAD

**Issue by ergcode** [elementary/terminal#525]
When working with this application, I found the following shortcomings:
- No search inside stdout (critical). Also, sometimes when searching, I need regular expressions.
- No bookmarks. Sometimes you have to work with projects and change them very quickly. In each project I need several local and remote addresses.
- No hotkey instruction.
- Cannot change hotkeys (critical).
- You cannot divide the window.
- No transparency setting.
- Cannot resize stored stdout (critical).

OS minimalism does not imply customization like Konsole. But search, stdout size and custom hotkeys are very important.

**Comment by danrabbit** [comment]
Hey thank you for filing these feature requests! It would really help our ability to track, assign, and discuss these features if each bullet point was its own separate issue report. It's not really possible to prioritize issues that are reported in a group like this.

As a general rule, we are unable to track grouped issue reports, so I will be closing this report as "Invalid". I would be happy to help triage and discuss these feature requests once they have their own individual reports. Thanks!

**Comment by ergcode** [comment]
> Hey thank you for filing these feature requests! It would really help our ability to track, assign, and discuss these features if each bullet point was its own separate issue report. It's not really possible to prioritize issues that are reported in a group like this.
> 
> As a general rule, we are unable to track grouped issue reports, so I will be closing this report as "Invalid". I would be happy to help triage and discuss these feature requests once they have their own individual reports. Thanks!

That is, you need to create a separate report for each function?

**Comment by danrabbit** [comment]
Yes that's correct
