### ISSUE TITLE
 Hash Sum mismatch

### ISSUE THREAD

**Issue by ElJo16** [elementary/terminal#543]
Hashes of expected file:
   - Filesize:173328 [weak]
   - SHA256:e3f89ca90517229513b031c2f0e742e9db36ec3e46ca78da7dbc2c40320b57ae
   - SHA1:39f383c711d0ff6d6efe5dcef7b1dbc384138557 [weak]
   - MD5Sum:44af836e49dbfa1ca723e38d954a2665 [weak]
  Hashes of received file:
   - SHA256:2f49ec263115dbf85cf6ce95860fac21c2fd67ba21272b437f166720be3cbbde
   - SHA1:b15aadf9005075d9826142e8581b5eebfef97dbd [weak]
   - MD5Sum:1e5131eadcb2e8663f2e6ee16e27a415 [weak]
   - Filesize:173328 [weak]
  Last modification reported: Tue, 01 Sep 2020 21:09:21 +0000
  Release file created at: Thu, 24 Sep 2020 19:36:55 +0000
Fetched 425 kB in 2s (258 kB/s)                                                                  
Reading package lists... Done
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/universe/dep11/by-hash/SHA256/e3f89ca90517229513b031c2f0e742e9db36ec3e46ca78da7dbc2c40320b57ae  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:173328 [weak]
    - SHA256:e3f89ca90517229513b031c2f0e742e9db36ec3e46ca78da7dbc2c40320b57ae
    - SHA1:39f383c711d0ff6d6efe5dcef7b1dbc384138557 [weak]
    - MD5Sum:44af836e49dbfa1ca723e38d954a2665 [weak]
   Hashes of received file:
    - SHA256:2f49ec263115dbf85cf6ce95860fac21c2fd67ba21272b437f166720be3cbbde
    - SHA1:b15aadf9005075d9826142e8581b5eebfef97dbd [weak]
    - MD5Sum:1e5131eadcb2e8663f2e6ee16e27a415 [weak]
    - Filesize:173328 [weak]
   Last modification reported: Tue, 01 Sep 2020 21:09:21 +0000
   Release file created at: Thu, 24 Sep 2020 19:36:55 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by cassidyjames** [comment]
This seems like a local issue with your Internet connection or a temporary issue with packages, and doesn't have anything to do with the Terminal app itself.
