### ISSUE TITLE
Add option to reload tab/restart shell

### ISSUE THREAD

**Issue by andreasfelix** [elementary/terminal#544]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
When installing new applications, changing config files or if one just wants to reset the current shell environment, it is necessary open a new shell. Currently the fastest way to achieve this is to duplicate the current tab and close the old one.

**Describe the solution you'd like**
Add a *Reload Tab* or *Restart Shell* option to the context menu of a tab.

![Slice 1](https://user-images.githubusercontent.com/24651767/96375945-71ee6d80-117c-11eb-8c18-fe0949a013c3.png)

**Describe alternatives you've considered**
Source config file, but this does not remove old config, does not reset the environment and can lead to duplicated paths in the `$PATH` variable:

```sh
. ~/.bashrc
```

Clear cache for program locations, but does not do anything else:
```sh
hash -r
```
Almost the same as opening a new tab, but does also not produce the same environment [(see here)](https://medium.com/@rajsek/zsh-bash-startup-files-loading-order-bashrc-zshrc-etc-e30045652f2e):
```sh
exec sudo --login --user $USER
# or
exec sudo -u $USER bash
```

**Comment by cassidyjames** [comment]
I'm a fan of the term `Reload` here, and that's what's used in Epiphany as well.
