### ISSUE TITLE
Shortcut [Ctrl + T] to open a new tab

### ISSUE THREAD

**Issue by stephdin** [elementary/terminal#545]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

While browsing the internet with Firefox or any other browser i'm used to open a new tab with [Ctrl + T]. I often use multiple tabs in Terminal (ssh sessions, development servers, htop, etc). So when i need a new shell i often press [Ctrl + T] and nothing happens and i have to use the mouse to click on the little plus icon. That's a little bit annoying and breaks my flow.

**Describe the solution you'd like**

It would be really nice if the shortcut [Ctrl + T] to open an new tab would be implemented.

**Existing work**

This shortcut is used in every browser i know. More importantly it's also used in Files to open a new tab there.

**Comment by jeremypw** [comment]
It seems `<Control>T` is an existing `bash` shortcut.

**Comment by stephdin** [comment]
Oh i see. Yeah, that makes sense. Maybe it would be good then, to include the shortcut in the right click context menu on the plus icon to better find it as a user. As i didn't know it was possible at all.
Thanks for the quick response

**Comment by jeremypw** [comment]
Yes, you are right - that context menu should have shortcuts shown.  That is the intention for all elementary menus - it just takes time to get round to them all.  I'll open a new issue for that and close this one as a design conflict.  Thanks.

**Comment by jeremypw** [comment]
Actually it not so easy - that context menu is provided by the Granite library, not Terminal. And different apps provide different shortcuts for new tab (usually either `<Ctrl>T` or `<Ctrl><Shift>T`.  Not sure how to get round that.

**Comment by jeremypw** [comment]
An issue is outstanding in Granite - https://github.com/elementary/granite/issues/184.

**Comment by janxkoci** [comment]
FYI all terminal emulators that I tried over the years (from Lubuntu, Xubuntu, gnome-terminal, terminator, tilix, and so on) all open new tab with Ctrl+Shift+T. Having any other shortcut would be very confusing to a lot of people.
