### ISSUE TITLE
Compound emojis are not handled correctly

### ISSUE THREAD

**Issue by aral** [elementary/terminal#558]
Terminal currently does not handle [compound emojis](https://eclecticlight.co/2018/03/15/compound-emoji-can-confuse/) properly.

## Steps to Reproduce

1. Paste this emoji into Terminal: 

```shell
echo '👨‍👩‍👧'
```

## What should happen

You should see the following output from the command:

```
👨‍👩‍👧
```

## What actually happens

You see the following output from the command:

```
👨‍👩‍ 👧
```
(Note: I’ve included a space before the last emoji here otherwise the compound emoji will display correctly in this issue.)

## Platform Information

```
OS: elementary OS 5.1.7 Hera x86_64 
Host: LabTop Mk IV 
Kernel: 5.4.0-58-generic 
Uptime: 7 days, 20 hours, 46 mins 
Packages: 2047 
Shell: zsh 5.4.2 
Resolution: 3840x2160 
DE: Pantheon 
WM: Mutter(Gala) 
Terminal: io.elementary.t 
CPU: Intel i7-10710U (12) @ 4.700GHz 
GPU: Intel Device 9bca 
Memory: 8454MiB / 15883MiB 
```

**Comment by danrabbit** [comment]
So the contents of the Terminal itself are not part of this codebase. I think this is probably the responsibility of `libvte`, so the issue report should be filed at https://gitlab.gnome.org/GNOME/vte

Closing as "out of scope" since we done control character rendering here

**Comment by aral** [comment]
I’m confused, isn’t fixing a bug in a dependency in-scope for an app? I’m pretty sure someone who sees that elementary Terminal cannot render emojis properly will not think “libvte” cannot render emojis properly but “elementary OS has issues… like it’s terminal app cannot render emojis properly.”

I’d recommend that this issue be kept open and someone assigned to ensure that the bug is fixed in libvte.

I don’t mind opening said issue and tracking it – i.e., I don’t mind taking this on – but I would argue that it is very much in-scope because as far as anyone using elementary OS Terminal is concerned, this is a bug with Terminal.

**Comment by danrabbit** [comment]
It's not really reasonable to track all dependency issues in each app's tracker, especially when there's nothing that can be done about it within this codebase. That's just not our policy regarding issue tracking. The more clutter there is in the tracker the harder it is to address actionable issues
