### ISSUE TITLE
Terminal tabs should use spinner for active tabs

### ISSUE THREAD

**Issue by hanaral** [elementary/terminal#561]
## Problem

There is no way to tell a tab is running a command until it is complete or you attempt to close the app.

## Proposal

Have a spinner like loading tabs in Files has if it is running a command (the macOS terminal does this too)

**Comment by danrabbit** [comment]
Closing as a duplicate of #317

**Comment by jeremypw** [comment]
No longer completed but not re-opening as duplicate.
