### ISSUE TITLE
Show clipboard contents in paste protection dialog

### ISSUE THREAD

**Issue by danrabbit** [elementary/terminal#562]
## Problem

I just went to past a string into Terminal and paste protection popped up. I was confused because the string I was pasting was not a command, but a branch name. Why is this dialog appearing? How weird. The string was `fix-sudo-extraneous-output` ;p

## Proposal

It would probably be helpful to show the string that will be pasted in the paste protection dialog so that the user can review it before deciding to continue or cancel

**Comment by cassidyjames** [comment]
This makes sense. I think just using the details expander to show the contents of the command would be a good start.

**Comment by jeremypw** [comment]
Presumable Terminal saw `sudo` and freaked out :stuck_out_tongue_winking_eye:

**Comment by igordsm** [comment]
It seems like terminal checks if the paste text contains `sudo` and has a newline character. Not sure why it would trigger for a branch name though.

The following screenshots use the details expander to show the commands to be pasted.

![Captura de tela de 2021-03-04 21-33-13](https://user-images.githubusercontent.com/221446/110049930-92852180-7d31-11eb-891c-a6f790fa59d7.png)

![Captura de tela de 2021-03-04 21-33-17](https://user-images.githubusercontent.com/221446/110049937-9618a880-7d31-11eb-8afa-ba43490ae4c5.png)

Would that work? I personally liked it.

**Comment by danrabbit** [comment]
@igordsm Yes that would work nicely! Awaiting your PR ;)
