### ISSUE TITLE
Terminal crashes when killing tasks

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/terminal#565]
## What Happened

Not sure if it belongs here or in [elementary/tasks](https://github.com/elementary/tasks). Killing Tasks via `killall io.elementary.tasks` kills `io.elementary.tasks` and crashes terminal.

## Expected Behavior

It shouldn't crash terminal.

## Steps to Reproduce

1. `killall io.elementary.tasks`

### Logs

Not sure where/how to retrieve logs here.

## Platform Information

Daily terminal.

**Comment by Marukesu** [comment]
The issue is, both names are too long to killall, and both processes end beginning `io.elementary.t`. you can see it by running `killall -i io.elementary.tasks`

**Comment by pongloongyeat** [comment]
I didn't even stop to think that the problem was with `killall`. I guess you learn new things everyday huh.

Closing since out of scope.
