### ISSUE TITLE
4-5% CPU usage for idle terminal

### ISSUE THREAD

**Issue by andreasfelix** [elementary/terminal#567]
I think I found a small-to-medium performance issue. I want to say in advance, I didn't spend much time investigating this. So I just opened this issue so it is documented. Maybe I can pick it up later or someone else decides to investigate this. 

The lines below introduce introduce a timeout which is never canceled. It saves the open terminals tabs **20 times** per second, which causes ~4-5% CPU and ~700 READ/WRITE syscall per second on my machine. (Increases with the number of tabs)

When looking at the debug logs (`G_MESSAGE_DEBUG=all`), one can also see that the open tabs are saved in a 50 ms interval.

<details>
  <summary>Debug Logs</summary>

```console
...
[DEBUG 15:30:39.288819] MainWindow.vala:1477: save open terminals!
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.288: change_fast
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.288: change_notify: /io/elementary/terminal/saved-state/zoom
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.288: change_fast
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.288: change_notify: /io/elementary/terminal/saved-state/tabs
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.288: change_fast
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.288: change_notify: /io/elementary/terminal/saved-state/tab-zooms
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.289: change_fast
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.289: change_notify: /io/elementary/terminal/saved-state/focused-tab
[DEBUG 15:30:39.339260] MainWindow.vala:1477: save open terminals!
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.339: change_fast
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.339: change_notify: /io/elementary/terminal/saved-state/zoom
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.339: change_fast
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.339: change_notify: /io/elementary/terminal/saved-state/tabs
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.339: change_fast
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.339: change_notify: /io/elementary/terminal/saved-state/tab-zooms
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.339: change_fast
(io.elementary.terminal:143665): dconf-DEBUG: 15:30:39.339: change_notify: /io/elementary/terminal/saved-state/focused-tab
```
</details>

If uncommenting these lines the CPU usages drops to 0-0.5%.

https://github.com/elementary/terminal/blob/12cb5d40825dc923aa49726ae90ec11f5b8ff40f/src/MainWindow.vala#L1423-L1433

---
**Edit:** the below does not make sense

<strike>
Is it possible that it should just be

```vala
if (check_for_tabs_with_same_name) {
   // ...
}
```
instead of

```vala
if (!check_for_tabs_with_same_name) {
   // ...
}
```
?
</strike>

**Comment by jeremypw** [comment]
`check_for_tabs_with_same_name ()` should only return `false` if there is a tab with a blank name which is only expected to occur temporarily. By default it returns `true` which will end the timeout loop. Under what circumstances are you getting this continuous loop? I cannot reproduce it.  Do you have a tab with a blank name?

**Comment by andreasfelix** [comment]
yes, if I log `terminal.window_title` it's an empty string, but the tab label still shows the folder name... sry i cannot help more.

https://github.com/elementary/terminal/blob/12cb5d40825dc923aa49726ae90ec11f5b8ff40f/src/MainWindow.vala#L1443-L1447

**Comment by andreasfelix** [comment]
Even though I don't see how this could be related at all, I think the cause off this issue is that I have a custom prompt...

1. I was able to reproduce it on another machine with an (almost) fresh install of eOS 6, by appending

```bash
PS1="custom prompt> "
```

to the `.bashrc`.

2. Another way to reproduce this issue seems to start a custom program e.g. (python/zsh...)

```
G_MESSAGES_DEBUG=all io.elementary.terminal -e python3
```

My guess would be that VTE relies on the default PS1 variable of the bash shell to compute the window_title... and this variable is not available in other programs like python/zsh or is different if one uses a custom PS1 variable.

**Comment by jeremypw** [comment]
I'll see if I can reproduce that - in which case the appropriate fix would be to ensure there is always a tab label, I think, although I suppose some limit on the number of times the Timeout loops waiting for a non-blank label could also be imposed.

**Comment by jeremypw** [comment]
I can confirm the issue with the custom prompt. This appears to be an issue with the Vte terminal widget - when there is a custom prompt set the `window_title` property returns `""` indefinitely :shrug:   So that breaks the logic of the code.  I guess we will just have to have a sufficient one-time timeout before checking for duplicates.

**Comment by jeremypw** [comment]
Although the cwd of a tab can be determined anytime, there seems no obvious way of being notified when it changes due to e.g. the user entering a `cd` command. Obvious the terminal widget manages it somehow *when there isnt a custom prompt* but when there is, the window and tab titles are just "Terminal" and do not update after a cwd change. Even e.g. the Mate Terminal suffers from this problem.  The only way around this seems to be to continuously poll the cwd e.g. when the terminal contents change.
