### ISSUE TITLE
Tabs with same name not disambiguated with custom prompt

### ISSUE THREAD

**Issue by jeremypw** [elementary/terminal#583]
## What Happened

Tabs with the same name are not disambiguated if a custom prompt is used

## Expected Behavior

Enough of the path to disambiguate the tab name should be used as the tab label.

## Steps to Reproduce

1 Edit `~/.bashrc` to include `PS1="custom prompt >"`
1 Open a tab at e.g. ..../xxx/build
2 Open a second tab at e.g. .../yyy/build
3. Both tabs are labelled "build"
4. Window title stays as "Terminal" regardless of selected tab

## Platform Information

Elementary 6 daily

**Comment by jeremypw** [comment]
I have now remembered that I changed my `.bashrc` file to show a custom prompt which stops the window title updating to show the path and, indirectly stops the code that disambiguates the labels running.  This is annoying as I do not want an excessively long prompt but I do want disambiguated tabs :disappointed: Not sure if there is a workaround for this.

**Comment by andreasfelix** [comment]
Doesn't this issue have the same cause as #567 ? And shouldn't that be also solved by your PR #568 ?

**Comment by jeremypw** [comment]
Huh - I'd completely forgotten about that.  This issue is described differently to #567 but you are right the underlying cause is the same part of the code. I have written a new PR which is quite similar to the old one (#568) but I think may be slightly better.
