### ISSUE TITLE
Empty area when maximizing or tiling

### ISSUE THREAD

**Issue by JoseExposito** [elementary/terminal#588]
## What Happened

When the terminal window is maximized or tiled to the right of the screen, an empty gap is created:

![Screenshot from 2021-05-28 07 31 51](https://user-images.githubusercontent.com/1335948/120070315-1f6a1d80-c08a-11eb-8128-9d365a57582d.png)

## Expected Behavior

All available space should be used.

## Steps to Reproduce

1. Maximize the window
2. The terminal doesn't use all the available space

## Platform Information

elementary OS Beta

**Comment by wedsonlopes** [comment]
I'm having the same issue here, I just came to report and realize that you and other members had already reported.

**Comment by andreasfelix** [comment]
I think this is a regression of #585. #589 should fix this.
