### ISSUE TITLE
[odin beta] No terminal bell any more

### ISSUE THREAD

**Issue by gvansanden** [elementary/terminal#596]
## What Happened
I ran ping -a in the new odin terminal and there was no sound

## Expected Behavior
The terminal bell should be heard to indicate that the server is up (it sends the bell character).
If the bell is disabled by default, a toggle to turn it back on would be nice

## Steps to Reproduce

1. Open a terminal
2. ping -a a server that is up

## Platform Information

* Elementary OS 6 (updated to 20210611)

**Comment by jeremypw** [comment]
There is a setting `io/elementary/terminal/settings/audible-bell` that defaults to `false`.  You need to change this to get the terminal bell. You can do this either with `dconf-editor` or at the command line with `gsettings set io.elementary.terminal.settings audible-bell true`

**Comment by jeremypw** [comment]
It could be argued that since it is supported, this setting should be exposed in the UI.

**Comment by jeremypw** [comment]
A complication of this is that the settings `org/gnome/desktop/wm/preferences/audible-bell`, `org.gnome.desktop.sound/event-sounds and `org/gnome/desktop/wm/preferences/visual-bell` also influence whether the Terminal bell setting has any noticeable effect.

**Comment by jeremypw** [comment]
@danirabbit Think more on it, is it necessary to have a separate setting for audible bell in Terminal? We can already control this globally in in System Settings/Sound.

**Comment by danirabbit** [comment]
@jeremypw i remember we added a separate option here because the bell sound was particularly obnoxious in terminal for some reason. I don't remember the specifics, it's worth looking at again probably since it's been years

**Comment by jeremypw** [comment]
@danirabbit OK, I'll leave the PR up for review then. To keep it simple, it does not try to reflect the state of other settings - the text just notes "subject to system settings".
