### ISSUE TITLE
Wrong locale code for Moldovan/Romanian

### ISSUE THREAD

**Issue by fmneto** [elementary/terminal#598]
The locale being used for Moldovan language is wrong. According to ISO-639-2 the correct code is 'ro'. Or if it has to be country-specific, 'ro-MD'. 

That might cause the locale to be missed by glibc, compromising localisation.

See:
[https://www.loc.gov/standards/iso639-2/php/code_list.php](https://www.loc.gov/standards/iso639-2/php/code_list.php)
[https://en.wikipedia.org/wiki/Moldovan_language](https://en.wikipedia.org/wiki/Moldovan_language)

**Comment by tintou** [comment]
Indeed, we should use `ro`

**Comment by fmneto** [comment]
`ro` is taken. Since the .po file claims to be for Moldovan, I created a pull request changing `mo` to `ro_MD` which should be the correct code.
