### ISSUE TITLE
Text size/zoom not remembered when closing tab

### ISSUE THREAD

**Issue by cassidyjames** [elementary/terminal#603]
## What Happened

@techdev5521 and I discovered this during/after his edw talk. If you close a tab specifically with its close button, with `exit` in the Terminal, or with <kbd>Ctrl</kbd><kbd>D</kbd>, Terminal will not save (and then later restore) that tab's text zoom.

## Expected Behavior

Closing a tab would save its text zoom, just like it does when closing the window.

## Steps to Reproduce

1. Open Terminal with a single tab
2. Set a new text size, e.g. 200%
3. Close that tab with the tab's close button, by typing `exit`, or by pressing <kbd>Ctrl</kbd><kbd>D</kbd>
4. Re-open Terminal and see the original zoom level

## Platform Information

elementary OS 6 beta 2 with Terminal from master

**Comment by jeremypw** [comment]
If you close a tab with its close button it could be argued that you are finished with that tab and therefore it would not be expected to be saved and restored. If what you really want to do is close the window then you should use the close window button or shortcut.

**Comment by jeremypw** [comment]
However, I guess if what you mean is that if what you mean is restoring with the restore button rather than restoring on re-opening Terminal then you have a point. I think at the moment the restore button only stores the url of the tab, not its zoom level.

**Comment by jeremypw** [comment]
Hm, it seems that the restore button *does* restore the zoom value because it actually stores the terminal widget.

**Comment by techdev5521** [comment]
> If you close a tab with its close button it could be argued that you are finished with that tab and therefore it would not be expected to be saved and restored. If what you really want to do is close the window then you should use the close window button or shortcut.

This might make sense in the cae of mouse centric users but does not lend itself well to keyboard navigation. I'd counter this logic by saying a user indicates they're finished with a task when they _either_ close the window _or_ end the shell session.

**Comment by jeremypw** [comment]
With the linked PR, closing the last tab saves its properties just as if the window had been closed directly.

**Comment by cassidyjames** [comment]
Yeah I think saving state when closing the last tab makes sense; there's little distinction to the user between closing the last tab versus closing the app, as the former causes the latter.

**Comment by hanaral** [comment]
Can I ask  why single view apps like Terminal don't disable the close button of the last tab anyway? Maybe there should starting page when all terminals are closed indicating that a tab needs to be opened again

**Comment by jeremypw** [comment]
It seems that a significant number of users habitually close the app by closing the last tab and would object if this behaviour were changed.
