### ISSUE TITLE
Terminal takes a long time asking for sudo password.

### ISSUE THREAD

**Issue by sirsleon** [elementary/terminal#612]
## What Happened

Terminal takes a long time to ask for sudo password when using a sudo command. With every sudo command it would take about 10s for terminal to ask me for my password.

## Expected Behavior

Ask sudo password a lot quicker than 10s.

## Steps to Reproduce

1. Type any sudo command like sudo apt install _ or sudo apt clean.
2. See how long it takes to ask for your sudo password.

### Logs

n/a

## Platform Information

elementary OS 6
Terminal 6.0.0

**Comment by cassidyjames** [comment]
I’m sorry, I can't reproduce this on any hardware here. Can you share some hardware details, like processor and hard drive?

**Comment by sirsleon** [comment]
Dual-Core Intel® Core™ i5-7300U CPU @ 2.60GHz
Intel® HD Graphics 620 (Kaby Lake GT2)
7.5 GiB memory

Lenovo Yoga 370

**Comment by sirsleon** [comment]
That's weird, it was really slow yesterday and the day before, now it's instant. I'll close this off for now until I find a way I can confidently reproduce.

**Comment by davidmhewitt** [comment]
Did you change your hostname after installation? If so, that'll be the cause.

Until you also make sure it's updated in `/etc/hosts` and reboot, this "problem" occurs in many Linux distros.

**Comment by sirsleon** [comment]
> Did you change your hostname after installation? If so, that'll be the cause.
> 
> Until you also make sure it's updated in `/etc/hosts` and reboot, this "problem" occurs in many Linux distros.

Ah yeah I changed hostname and didn't change that file too, hopefully this will prevent it from happening.
