### ISSUE TITLE
Option to disable reloading a tab with F5

### ISSUE THREAD

**Issue by atsuya** [elementary/terminal#617]
## Problem
I use [ctrlp](https://github.com/kien/ctrlp.vim) in vim, and ctrlp uses F5 to refresh a list of files to search against. Terminal intercepts F5 and tries to reload a tab, and it prevents ctrlp from refreshing the list of files.

## Proposal
It would be great if Terminal provides an option to disable this behavior.

## Prior Art
N/A.

Thanks!

**Comment by jeremypw** [comment]
We try to avoid adding options if possible - a better solution may be for Terminal to only respond to `F5` *after* a foreground process has ignored it.

**Comment by jeremypw** [comment]
This also affects e.g. `htop` where `F5` is used to switch to tree view.

**Comment by anhel-strauke** [comment]
Midnight Commander also is affected: <Esc> <5> works, but <F5> for file copying is more convenient.

At least hidden setting (like `/io/elementary/terminal/settings/alt-changes-tab`, for example) will do the trick.
