### ISSUE TITLE
Some characters are incorrectly escaped in links in Terminal

### ISSUE THREAD

**Issue by catamorphism** [elementary/terminal#625]
### What Happened?

When clicking on a link in a Terminal window, the character '#' is escaped when it shouldn't be, so the link the browser sees includes '%23' instead of '#'.

### Steps to Reproduce

In a Terminal window:
1. cat > test.txt
 - `https://treeherder.mozilla.org/#jobs
  ^D`
2. cat test.txt
3. Click on the link.
4. Notice that in the browser URL bar, what appears is `https://treeherder.mozilla.org/%23/jobs`.

### Expected Behavior

I would expect the link to be passed to the browser literally without escaping the '#'.

### OS Version

6.x (Odin)

### Software Version

Older release (I have not run all updates)

**Comment by hollyschilling** [comment]
I have a fix for this coded up locally. Before posting a PR, I'd like to add some unit testing around the URI Encoding. @jeremypw Could you connect with me to talk through how to add them to the project?

**Comment by jeremypw** [comment]
@hollyschilling Thanks for working on this! There are a few elementary repos containing examples of unit testing. Probably the simplest is in Calculator as it consists of only two files in a `tests` folder. Presumably you will simply be processing a range of URLs and comparing the result with the correct answer so you shouldn't need anything complicated?  Further information abut the meson test framework can be found at https://mesonbuild.com/Unit-tests.html but copying an existing example is usually easiest!
