### ISSUE TITLE
open

### ISSUE THREAD

**Issue by Asfarial** [elementary/terminal#634]
### Problem

Terminal does not have such command as "open", which is really usefull.

### Proposal

Please, consider the following Script.

#!/bin/bash
if [[ $# -gt 1 ]]; then
	echo "$0: error - to many arguments - use only 1 argument" >&2
	exit 1
elif [[ ! -r $1 ]]; then
	echo "$0: file doesn't exist: \`$1'" >&2
	exit 1
else
	xdg-open "$1" > /dev/null 2>&1 & disown
fi
exit 0

**Comment by jeremypw** [comment]
@Asfarial I presume you want to be able to type `open <app-name>` at the bash prompt? In which case this is not really a Terminal issue - you need to create an alias/bashscript (or elementary would have to ship one by default, which is unlikely).  Is it OK to close this as "Out of Scope"?
