### ISSUE TITLE
Keyboard adding random characters

### ISSUE THREAD

**Issue by ItsJamie9494** [elementary/terminal#636]
### What Happened?

if I type a `'` character, it autocorrects to `./`
if i type a `/` character, it autocorrects to `./`
if i type a `?` or `>` character, it autocorrects to `>?`

### Steps to Reproduce

1. Open literally any app
2. Type a `.` character

### Expected Behavior

It should only type `.` instead of `./`, etc

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

NVIDIA 2060, and Razer Cynosa Chroma keyboard

**Comment by jeremypw** [comment]
If it is affecting all apps then it seems unlikely to be an elementaryos problem unless confirmed on a different system.  Have you setup any macros or remapped the keys on the keyboard?  Any other non-standard software or settings?

**Comment by jamiethalacker** [comment]
I have not seen it on a different system, and I've used multiple distros on this machine before. I have not remapped any keys or setup any macros. Only non-standard software would be the OpenRazer driver I installed to try and fix the issue.
I do not have a spare keyboard to test with, and I didn't know elementary had an on-screen keyboard

**Comment by jeremypw** [comment]
There should be an app called "Onboard" available in Applications which provides an on-screen keyboard.  Confusingly, the name rather clashes with the onboarding program also provided by elementary and it is not available in the AppCenter.  I do not remember installing it myself but if you do not have it, it is in the Ubuntu repositories so you can install it with `sudo apt install onboard`

**Comment by jamiethalacker** [comment]
I tested with the Onscreen keyboard, and the issue wasn't there. So it's only on my physical keyboard

**Comment by jeremypw** [comment]
In that case it is unlikely to be a Terminal issue.

**Comment by jamiethalacker** [comment]
I don't know what other repository to submit the issue to

**Comment by jeremypw** [comment]
I guess https://github.com/elementary/triage/issues as it is not clear what is causing this issue.
