### ISSUE TITLE
How can I solve this elementary OS terminal error?

### ISSUE THREAD

**Issue by MathewFreddickRiddle** [elementary/terminal#657]
### What Happened?

Hello!

I want to tell you that in terminal I can't install packages, they just return me a error.

For example:

`sudo apt install dconf-tools Reading package list... Done Creating dependency tree Reading status information... Done E: Failed to locate package dconf-tools
`

And also with:

```
sudo apt install kubuntu-desktop
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
E: No se ha podido localizar el paquete kubuntu-desktop

```I appreciate any help!



### Steps to Reproduce

1. Open the terminal.
2. Write installer command.
3. Get the error.
 ![ An screenshot](https://i.ibb.co/bvTQGWG/e-OS-Error.png)

### Expected Behavior

The program/application should have been installed.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

**Comment by jeremypw** [comment]
`dconf-tools` was removed from the Ubuntu repository for 20.04 - see https://askubuntu.com/questions/1248426/what-has-replaced-dconf-tools-for-ubuntu-20-04.  I am not sure what you want to achieve but I use `dconf-editor`.  You can list dconf related packages available with `sudo apt search dconf`

`kubuntu-desktop` is present in the elementary 6 (focal) repository so you should be able to install it (although not recommended - you can install individual kde apps if you want).

You can install an app like `synaptic` to get more detail about what repositories are installed and what is in them.

Closing this issue as it is not a Terminal code problem.
