### ISSUE TITLE
Minimized option

### ISSUE THREAD

**Issue by Obema12** [elementary/terminal#681]
There is currently no such option:

```
Application Options:
  -v, --version Show version
  -e, --execute=COMMAND Run a program in terminal
  -x, --commandline=COMMAND_LINE Run remainder of line as a command in terminal. Can also use '--' as flag
  -n, --new-window Open a new terminal window
  -t, --new-tab Open a new terminal tab
  -h, --help Show help
  -w, --working-directory=DIR Set shell working directory
  --display=DISPLAY X display to use
```

Could you add the ability to launch with the `-m, --minimized` option which will launch the terminal minimized in plank?

**Comment by jeremypw** [comment]
What are the use cases for this?

**Comment by Obema12** [comment]
It's just aesthetically beautiful when, after loading the system, you see your desktop, and not applications that are launched in turn. Yes, rather with `-e`.
