### ISSUE TITLE
Terminal launched without restoring tabs overwrites saved tabs on saving

### ISSUE THREAD

**Issue by jeremypw** [elementary/terminal#707]
### What Happened?

If Terminal is launched with the `-x` option e.g. `io.elementary.terminal -x htop` then closing that window will overwrite any previously saved tabs and the next "normal" launch will not be able to restore them.

### Steps to Reproduce

1. Open several tabs  (with History ON)
2. Close normally
3. Run `io.elementary.terminal -x htop` in a script or different terminal app
4. Close normally
5. Open normally - original tabs not restored.

### Expected Behavior

If Terminal is launched in a way that inhibits the normal restoration of tabs it should not overwrite saved tabs when it closes.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by Marukesu** [comment]
I can't reproduce this in master, the tabs are always saved and restored in the next launch. with and without `-x`.

**Comment by jeremypw** [comment]
Hmm - I must have had different branch or version of Terminal installed - its easy to lose track!  Its an open question whether all tabs *should* be restored when you only want to run a process in one tab in a temporary terminal but as long as they are, this issue will not arise.
