### ISSUE TITLE
Clickable Terminal Toggle

### ISSUE THREAD

**Issue by treppenwitz03** [elementary/terminal#708]
### Problem

Prior to the recent release which incorporated the terminal into the program instead of being a plugin, a button toggle in the HeaderBar allowed easy showing or hiding of the terminal. However, it was removed in the latest release, and to toggle the terminal, the shortcut "Ctrl + Alt + T" was used instead. Personally, I find it harder to do than just clicking on a button which is why I found myself just opening a new terminal window and "Alt + Tab"-ing which is easier for my hands to do.

### Proposal

**1.) Restore the terminal toggle button in the HeaderBar (might cause** 
This might go against the recent changes to make the app fit in smaller display sizes, but if I am to choose whether to have the terminal button or the tab width, language, and line number indicator  in an unmaximized window, I would prefer to have the terminal toggle button.
**2.) Replace the shortcut with something familiar but easier to do with the hands**
This might work against the system-wide shortcut for terminal if I am not mistaken.

**Comment by danirabbit** [comment]
Hey thanks for your report! You can toggle the Terminal pane from the app menu along with the project pane and outline pane. It’s the button that shows a pane coming from the bottom of the window

closing since there is still a button to toggle the terminal pane
