### ISSUE TITLE
When creating a new terminal window with the setting the working directory, there is an additional tab that starts at the working directrory

### ISSUE THREAD

**Issue by colinkiama** [elementary/terminal#736]
### What Happened?

When I run this command for example:
```sh
io.elementary.terminal -n -w my_new_directory
```
A new terminal window opens with 2 tabs:
1. Current working directory is the `$HOME` directory
2. Current working directory is `my_new_directory`.

Only tab 2 should be open.

### Steps to Reproduce

1. Open the terminal app
2. Enter this command in the terminal app: `io.elementary.terminal -n -w ~/Downloads`
3. A new terminal window will appear with a tab where the current working directory is the home directory and a second tab where the current working directory is the "Downloads" folder.-

### Expected Behavior

A new terminal window should open with just one tab where the current directory is what I specified in the command I use to open a new terminal window.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by Gabriel-p** [comment]
I'm getting an extra tan in the $HOME dir every time I open the Terminal from its icon (i.e., not from a folder). Is this the default behaviour or is this related to this bug?

**Comment by jeremypw** [comment]
@Gabriel-p I don't think it should be the default behaviour  (Code does not open a new document every time it opens). I'll try to get my PR #743 into a reviewable state.
