### ISSUE TITLE
The F11 shortcut key causes the maximize/unmaximize button to fail, in termial,

### ISSUE THREAD

**Issue by gasensorX** [elementary/terminal#752]
### What Happened?

The F11 shortcut key causes the maximize/unmaximize button to fail.  Double-clicking on the title bar also does not restore. The only way to recover is to press F11 again. Double-clicking on the title bar also does not restore.  The default maximization shortcut is Super+Up. I can't figure out where this F11 shortcut came from.

### Steps to Reproduce

1. Open a Terminal.
2. Press F11.
At this time,  the maximize/unmaximize button is disabled.  Double-clicking on the title bar also does not restore.

### Expected Behavior

At any time, it should be possible to maximize or exit by double-clicking on the title bar. Or  press super+up

### OS Version

7.x (Horus)

### Software Version

Older release (I have not run all updates)

### Log Output

```shell
It is not possible to update flatpak in China.
```

**Comment by jeremypw** [comment]
`F11` is for "full-screening" the app, which is different from maximising and usually results in the headerbar disappearing.  The other difference is that the app window overlays the wingpanel and dock when full-screened but not when maximised. It is normal for full-screen to be reversed by pressing `F11` again.  Some apps (e.g. Chrome) also provide some other way of reversing it.

This is really a window manager issue as it affects any app that keeps its headerbar when full-screened. For example Code has the same issue.  Some apps, for example Files, simply disallow full-screening as the headerbar is essential.  That is probably the simplest solution here.  There is no particular advantage in full-screening a terminal compared to maximising it.

**Comment by jeremypw** [comment]
On further thought a less invasive solution is to hide the header decorations when full-screened.
