### ISSUE TITLE
Add command autocomplete 

### ISSUE THREAD

**Issue by diogopessoa** [elementary/terminal#764]
### Problem

None

### Proposal

This feature can make using the terminal easier and faster for the user.

### Prior Art (Optional)

Examples:

![Captura de tela de 2024-07-11 20 54 16](https://github.com/user-attachments/assets/486834cf-2158-4c8f-891f-214f844aac02)
![Captura de tela de 2024-07-11 20 51 27](https://github.com/user-attachments/assets/22fbaa3c-d7a8-4475-808f-6cccb17881fe)
![Captura de tela de 2024-07-11 20 50 55](https://github.com/user-attachments/assets/08f3f85e-1150-42f3-b682-dec3f41da87f)
![Captura de tela de 2024-07-11 20 48 50](https://github.com/user-attachments/assets/87810d1a-5956-4ab0-8a86-889d792335ad)

**Comment by danirabbit** [comment]
I think the realistic way to do this would be to change the default shell to fish or zsh.

There's a discussion post about zsh here: https://github.com/elementary/terminal/discussions/555

**Comment by diogopessoa** [comment]
Indeed!

ZSH has autocomplete and other features.

Thank you Danielle.
