### ISSUE TITLE
Fails to build in Launchpad due to tests

### ISSUE THREAD

**Issue by danirabbit** [elementary/terminal#806]
### What Happened?

Currently daily fails to build because of tests

### Steps to Reproduce

https://launchpadlibrarian.net/759144852/buildlog_ubuntu-noble-amd64.io.elementary.terminal_6.2.0+r2595+pkg88~daily~ubuntu8.1_BUILDING.txt.gz

### Expected Behavior

passing tests or we skip tests during package build

### OS Version

8.x (Early Access)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
From the log it looks like `Vte.get_user_shell ()` is returning `""` under the CI environment and there is no further fallback.  What would be a suitable hardcoded(?) path to use as an ultimate fallback?

**Comment by jeremypw** [comment]
Looks like the default directory `GLib.Environment.get_current_dir ()` is returning `""` under CI conditions.  I'll propose a PR with a hardcoded ultimate fallback for consideration.
