### ISSUE TITLE
Notifications are not withdrawn

### ISSUE THREAD

**Issue by teamcons** [elementary/terminal#812]
### What Happened?

I have old notifications from Terminal - Process ended with errors, process ended
Most were addressed (terminal focused)
A lot of them are from one or two sessions ago. So long obsolete

### Steps to Reproduce

receive notifications from terminal
never withdrawn

### Expected Behavior

terminal should withdraw addressed notifications

### OS Version

8.x (Circe)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
We should probably have like an ID per tab so we can replace when it makes sense and then yes focusing a tab should withdraw notifications for that tab. Good call
