### ISSUE TITLE
New window created with `<Ctrl><Shift>N' has zero tabs and is transparent

### ISSUE THREAD

**Issue by jeremypw** [elementary/terminal#814]
### What Happened?

Pressed `<Ctrl><Shift>N`.  A (small) new window appeared with the background showing through where the tab should be.

### Steps to Reproduce

1. Open Terminal
2. Press '<Ctrl><Shift>N`

### Expected Behavior

The new window should contain one default tab

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Compiled from git

**Comment by jeremypw** [comment]
When a new window is opened by entered `io.elementary.terminal -n` into an existing Terminal, a correct new window appears.

**Comment by teamcons** [comment]
Can reproduce on OS 8, Wayland

![image](https://github.com/user-attachments/assets/61e02866-5919-4942-b77c-a92cd8424646)
