### ISSUE TITLE
Reset action uses Ctrl+K as hotkey

### ISSUE THREAD

**Issue by bobby285271** [elementary/terminal#819]
### What Happened?

I am a very heavy [nano](https://nano-editor.org/) user (yeah...) and when testing [6.3.0](https://github.com/elementary/terminal/releases/tag/6.3.0) I found myself when doing <kbd>Ctrl</kbd> + <kbd>K</kbd> in nano it no longer cuts the line but instead reset the session (<kbd>Ctrl</kbd> + <kbd>K</kbd> is the hotkey in nano to cut a line), I believe this is introduced in https://github.com/elementary/terminal/pull/778.

It will be nice if there is a way to opt-out that (use another key, or remove the hotkey, or make it configurable, or anything...), though for now I guess i will just patch my own installation, assuming it is hardcoded... :joy:

https://github.com/elementary/terminal/blob/b113a966e5f9b506576224645e566ec32a98a79f/src/Widgets/TerminalWidget.vala#L78

https://github.com/elementary/terminal/blob/b113a966e5f9b506576224645e566ec32a98a79f/src/Widgets/TerminalWidget.vala#L450-L453

<img src="https://github.com/user-attachments/assets/84ec428a-c46a-4814-b416-f0020a8a26df" width=50%>

### Steps to Reproduce

1. Open terminal and run `nano some_file`
2. Type random stuff
3. <kbd>Ctrl</kbd> + <kbd>K</kbd>

### Expected Behavior

1. The hotkey is handled by nano instead of the terminal :joy:

### OS Version

NixOS

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by vjr** [comment]
Isn't there a "natural copy-paste" option you can disable in terminal?

**Comment by jeremypw** [comment]
This is related to issue #629.  Ideally foreground processes should have priority when processing key presses but I am not sure if this is possible with action accelerators.  Maybe we should use a more complicated hotkey like `<Shift><Ctrl>K` for this action as it is potentially destructive?
