### ISSUE TITLE
The new terminal (v6.3.0) is destroying current process on Ctrl-L

### ISSUE THREAD

**Issue by adayoung** [elementary/terminal#820]
### What Happened?

The elementary terminal (v6.2.0) used to work fine and pressing Ctrl-L in it would clear the screen as expected of a terminal. The new terminal released two days ago (v6.3.0) still clears the screen but kills the current process in doing so. So if I'm logged in with SSH to a remote machine, pressing Ctrl-L kill the SSH session and drops me in the / path on my local system. 

### Steps to Reproduce

1. Open elementary terminal
2. Type `ls` or any command. Heck, even switch to root with `sudo su -`. Or SSH into some remote machine
3. Press Ctrl-L, watch the session die, watch the screen clear, watch the current working directory switch to `/`

### Expected Behavior

Pressing Ctrl-L should clear the screen only and it should NOT kill the current process or change the current working directory.

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Using `G_MESSAGES_DEBUG=all io.elementary.terminal -n` does not produce any logs :-(
```

**Comment by adayoung** [comment]
It looks like #778 is the culprit in this one too :slightly_smiling_face:

**Comment by teamcons** [comment]
Present in 8 with Wayland.

> Sleep 20
Ctrl+L
resets the whole terminal, changes CWD to /

**Comment by adayoung** [comment]
From the discussion [here on askubuntu](https://askubuntu.com/questions/434240/ctrll-in-terminal) and the reference [here in readline's manual](https://www.gnu.org/software/bash/manual/html_node/Readline-Movement-Commands.html), it looks like Ctrl-L is interpreted by bash and things like IPython (and whatever uses readline) to clear the screen. The latest release of elemental terminal overrides that and consequently breaks the existing functionality for everyone 🙁

**Comment by rezk2ll** [comment]
i have the same issue:

elementary OS `7.1 Horus`
io.elementary.terminal: `6.3.0`

**Comment by jeremypw** [comment]
I think the problem is that the Clear Screen action uses the `clear -x` command which it runs in the current terminal. This stops any existing program from running. I'm not sure it is possible to clear the screen while keeping a program is running in it (except via that program).  The easiest solution is to ignore or disable the clear (and reset) actions while there is a foreground process running.  Another possible solution is to throw a confirmation dialog in a similar way to when an attempt to close a tab containing a running foreground process. The accelerators would still be consumed so not available for the foreground process so any clash with a popular terminal program needs to be flagged up.

**Comment by adayoung** [comment]
>  The easiest solution is to ignore or disable the clear (and reset) actions while there is a foreground process running.

This will still break Bash's handling of Ctrl-L. The current implementation of Ctrl-L in the elementary terminal destroys background jobs as well. Here, try this to reproduce the case:

1. Open elementary terminal (v6.3.0)
2. Launch something in the background, like `sleep 300 &`
3. Check background jobs with `jobs`
4. Hit Ctrl-L, watch the session die, watch the current working directory change to /
5. Check background jobs with `jobs` again, the list is empty. Our background process is gone!

> The accelerators would still be consumed so not available for the foreground process so any clash with a popular terminal program needs to be flagged up.

Eep eep eating up the Ctrl-L combination and not letting it reach the foreground program isn't any better. It will break a lot of programs that use the [readline](https://www.gnu.org/software/bash/manual/html_node/Readline-Interaction.html) library for handling input. This includes Bash, IPython, nano, Ruby shell, Scala shell, and possibly a lot of other repl environments that depend on it.

Please either let us disable or redefine the keyboard accelerators in terminal instead if possible.

The terminal is a most excellent (and beautiful) piece of work otherwise :slightly_smiling_face:

**Comment by jeremypw** [comment]
I have now changed the hotkeys for the clear and reset actions to be `<Shift><Control>K` , `<Shift><Control>L` Hopefully this will prevent or minimise clashes with foreground processes.
