### ISSUE TITLE
The new terminal (v6.3.0) is opening with ever increasing geometry

### ISSUE THREAD

**Issue by adayoung** [elementary/terminal#821]
### What Happened?

The elementary terminal application (v6.2.0) used to open with the fixed size in the middle of the screen. The new terminal released two days ago (v6.3.0) keeps opening with ever increasing window size which amounts to a pretty poor user experience.

### Steps to Reproduce

1. Open the elementary terminal from the application launcher
2. Close it either by clicking the close button or pressing Ctrl-D
3. Open it again, watch it open with a slightly larger size
4. Keep repeating steps 2 and 3 and eventually a new terminal window occupies the entire screen like a Christmas monster

### Expected Behavior

It was fine the way it was before. Be nice if it remembered how big it was but it doesn't have to keep increasing in size with every summon.

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Using `G_MESSAGES_DEBUG=all io.elementary.terminal -n` did not produce any logs :-(
```

**Comment by teamcons** [comment]
Cannot reproduce on Wayland

**Comment by jeremypw** [comment]
I can reproduce on 7.1 (X) - the window dimensions increase by 100px each time it is closed and opened. Not immediately obvious which commit was the culprit - possibly https://github.com/elementary/terminal/pull/783/files. I can confirm it does not happen on OS8 (Wayland).  I'll try to find a solution that works on both.

**Comment by jeremypw** [comment]
The change was in preparation for porting to Gtk4 and followed the pattern of other elementary apps.

**Comment by jeremypw** [comment]
I can confirm that the draft Gtk4 port of Terminal works OK on both Wayland and X.  So it looks like an upstream bug in window size control.  I'll try reverting that suspect commit.

**Comment by jeremypw** [comment]
@adayoung I have pushed a PR that fixes the issue - thanks for bringing it to our attention.

**Comment by adayoung** [comment]
Thank you for looking into it :smiling_face_with_three_hearts:
