### ISSUE TITLE
CTRL+L changes directory to /

### ISSUE THREAD

**Issue by carniz** [elementary/terminal#828]
### What Happened?

I noticed that hitting CTRL+L (which should just clear the screen) now results in changing directory to `/`.

### Steps to Reproduce

1. Be somewhere else than `/`
2. Press CTRL+L
3. Type `pwd`
4. You are now in `/`

### Expected Behavior

You're still somewhere else than `/`

### OS Version

7.x (Horus)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Thanks for the report, but this issue is included in report #820 for which a fix has been merged and should be released soon.

Closing as fixed.
