### ISSUE TITLE
Cannot exit terminal/tab opened with '-e' option.

### ISSUE THREAD

**Issue by cgroner** [elementary/terminal#91]
Normally, when finished with a terminal tab I can type `exit` to close the tab. However, when new tabs are opened with the `-e` flag typing `exit` no longer closes the tab.

Steps to reproduce:

1. From the terminal, type `pantheon-terminal -e "sleep 1"`. You should see a new terminal tab, and after a second the sleep command should finish and you should see the prompt.

2. Type `exit`.

Actual results: The tab remains active.

Expected results: The tab should be closed.

**Comment by jeremypw** [comment]
Probably a regression due to commit dc9d49fe3634ad04f95c95c10b4806a9699f3ca8 (#82)

**Comment by davidmhewitt** [comment]
I guess we only want to ignore only the `child_exited` signal. The rest are probably still valid.
