### ISSUE TITLE
Cannot exit from restored tab.

### ISSUE THREAD

**Issue by cgroner** [elementary/terminal#94]
Once a terminal tab has been closed and restored, typing `exit` in the terminal does not close the tab. Additionally, closing the tab using the close 'x' in the UI causes a segmentation fault.

Steps to reproduce:

1. Open new tab.
2. Close newly opened tab using the close 'x' in the tab UI.
3. Reopen the tab by right clicking tab bar and selecting the "Undo Close Tab" entry.
4. In the reopened terminal, type `exit`.

I would expect typing 'exit' in step 4 would close the tab and it remains open. Clicking the close 'x' button in the tab UI then triggers a segfault.

pantheon-terminal version: 0.4.2

**Comment by cgroner** [comment]
It appears that the [signal handler](https://github.com/elementary/terminal/blob/12d615e456037e77baab1051fe9450a439b93efc/src/PantheonTerminalWindow.vala#L572) added to the `TerminalWidget` to close the terminal tab is somehow getting disconnected after the tab is initially closed and subsequently not called again.

This also seems to be happening to the [`window_title_changed` signal handler](https://github.com/elementary/terminal/blob/12d615e456037e77baab1051fe9450a439b93efc/src/TerminalWidget.vala#L146), which is likely the cause of bug #88.

**Comment by LightSunrider** [comment]
Fixed by #126
