### ISSUE TITLE
On fresh install, the Terminal window size is very small

### ISSUE THREAD

**Issue by uncertainquark** [elementary/terminal#96]
![screenshot from 2017-05-19 18-55-48](https://cloud.githubusercontent.com/assets/22585732/26249586/bb074dac-3c96-11e7-99d0-feaf45bfdfc2.png)

A more comfy quarter of a screen would be nice as this one is too small to not fit even small commands in one line.

I am sorry if I am nitpicking but its a small thing that can matter.

**Comment by cassidyjames** [comment]
@elementary/ux I agree and have noticed this; I always size it up. What should the default be (keeping in mind in Loki, Mutter includes the shadow as part of the window size request)?

**Comment by danrabbit** [comment]
I think last time we looked at this, @codygarver had a reason for keeping the default Terminal size very small

**Comment by vjr** [comment]
Was it due to the possibility of low-res screens or regular screens with bad gfx configs (causing low-res again), in which scenario being able to open a terminal and work on fixup commands is ideal?

Could the size not just be computed to say half the length and width and window centered, so it's appropriate for whatever screen res shows up?

**Comment by vjr** [comment]
It's currently hardcoded here: https://github.com/elementary/terminal/blob/master/org.pantheon.terminal.gschema.xml#L22

If we can set those values to -1 (like the initial x/y pos) then calculate it at startup similar to https://github.com/elementary/terminal/blob/master/src/PantheonTerminalWindow.vala#L332 then that would be cool.

Let me see if I can propose a PR here :-)

**Comment by vjr** [comment]
Correct PR link is https://github.com/elementary/terminal/pull/119
