### ISSUE TITLE
feature request: option to move close-button "X" to right-side

### ISSUE THREAD

**Issue by meoso** [elementary/terminal#97]
feature request: option to move the close-button "X" to right-side of tabs.

I realize, Elementary likes most all buttons on left-side, but a large percent of users prefer all buttons right-side and use [tweaks](https://github.com/elementary-tweaks/elementary-tweaks) to set these.  However, the pantheon terminal does not seem to have any programmability to set the close button to the right-side of the tabs.

**Comment by danrabbit** [comment]
Since Terminal gets its tab widget from [Granite](https://github.com/elementary/granite) it doesn't have control over this. Marking as "Invalid" for Terminal.
